<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Chapter 1: Deryugina (2017) — Hurricane Hits and Government Transfers – Applied Examples with did_multiplegt_dyn</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch02.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-8b4baf804e461d9b72633f0de59a0cac.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-edaf08ed7d27d62012077beed0893dcb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ch01.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Ch. 1 — Deryugina (2017)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Applied Examples with did_multiplegt_dyn</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Ch. 1 — Deryugina (2017)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ch. 2 — East et al.&nbsp;(2023)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Ch. 3 — Gentzkow et al.&nbsp;(2011)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ch. 4 — Hollingsworth et al.&nbsp;(2022)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#t1-verify-one-shot-design" id="toc-t1-verify-one-shot-design" class="nav-link active" data-scroll-target="#t1-verify-one-shot-design"><span class="header-section-number">1.1</span> T1: Verify One-Shot Design</a></li>
  <li><a href="#t2-non-normalized-event-study-effects-no-controls" id="toc-t2-non-normalized-event-study-effects-no-controls" class="nav-link" data-scroll-target="#t2-non-normalized-event-study-effects-no-controls"><span class="header-section-number">1.2</span> T2: Non-Normalized Event-Study Effects (No Controls)</a></li>
  <li><a href="#t3-non-normalized-event-study-effects-with-county-level-controls" id="toc-t3-non-normalized-event-study-effects-with-county-level-controls" class="nav-link" data-scroll-target="#t3-non-normalized-event-study-effects-with-county-level-controls"><span class="header-section-number">1.3</span> T3: Non-Normalized Event-Study Effects (With County-Level Controls)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 1: Deryugina (2017) — Hurricane Hits and Government Transfers</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Research Question:</strong> How do hurricanes affect non-disaster government transfer programs in the United States?</p>
<p><strong>Data:</strong> County-year panel. Treatment <code>hurricane</code> is binary and non-absorbing (counties are treated for at most one year — a “one-shot” design). Outcome: <code>log_curr_trans_ind_gov_pc</code> (log non-disaster government transfers per capita).</p>
<hr>
<section id="t1-verify-one-shot-design" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="t1-verify-one-shot-design"><span class="header-section-number">1.1</span> T1: Verify One-Shot Design</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install did_multiplegt_dyn, <span class="kw">replace</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>copy <span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.dta"</span> <span class="st">"deryugina_2017.dta"</span>, <span class="kw">replace</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"deryugina_2017.dta"</span>, <span class="kw">clear</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">egen</span> total_hurricane = <span class="kw">total</span>(hurricane), <span class="kw">by</span>(county_fips)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">sum</span> total_hurricane</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
total_hurr~e |     49,698    .3163709    .4650642          0          1</code></pre>
<p>All counties have <code>total_hurricane</code> ∈ {0, 1} — confirming the one-shot design.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("DIDmultiplegtDYN", "polars", "haven", "dplyr"))</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtDYN)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(polars)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.RData"</span>))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_fips) <span class="sc">%&gt;%</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_hurricane =</span> <span class="fu">sum</span>(hurricane, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(total_hurricane), <span class="at">sd =</span> <span class="fu">sd</span>(total_hurricane),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">min =</span> <span class="fu">min</span>(total_hurricane), <span class="at">max =</span> <span class="fu">max</span>(total_hurricane))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code># A tibble: 1 × 4
   mean    sd   min   max
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.316 0.465     0     1</code></pre>
<p>All counties have <code>total_hurricane</code> ∈ {0, 1} — confirming the one-shot design.</p>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pip install py-did-multiplegt-dyn pandas pyarrow</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> did_multiplegt_dyn <span class="im">import</span> DidMultiplegtDyn</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_parquet(<span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.parquet"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> df.groupby(<span class="st">"county_fips"</span>)[<span class="st">"hurricane"</span>].<span class="bu">sum</span>().reset_index(name<span class="op">=</span><span class="st">"total_hurricane"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(total[<span class="st">"total_hurricane"</span>].describe())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>count    4518.000000
mean        0.316371
std         0.465064
min         0.000000
max         1.000000</code></pre>
<p>All counties have <code>total_hurricane</code> ∈ {0, 1} — confirming the one-shot design.</p>
</div>
</div>
</div>
<hr>
</section>
<section id="t2-non-normalized-event-study-effects-no-controls" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="t2-non-normalized-event-study-effects-no-controls"><span class="header-section-number">1.2</span> T2: Non-Normalized Event-Study Effects (No Controls)</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install did_multiplegt_dyn, <span class="kw">replace</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>copy <span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.dta"</span> <span class="st">"deryugina_2017.dta"</span>, <span class="kw">replace</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"deryugina_2017.dta"</span>, <span class="kw">clear</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn log_curr_trans_ind_gov_pc county_fips <span class="fu">year</span> hurricane, <span class="kw">effects</span>(11) placebo(11) <span class="kw">cluster</span>(county_fips)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>--------------------------------------------------------------------------------
             Estimation of treatment effects: Event-study effects
--------------------------------------------------------------------------------

             |  Estimate         SE      LB CI      UB CI          N  Switchers
-------------+------------------------------------------------------------------
    Effect_1 |  .0108629    .001617   .0076937   .0140321      14240        361
    Effect_2 |  .0127918   .0023651   .0081563   .0174273      13953        361
    Effect_3 |  .0158005   .0030075   .0099059    .021695      13766        361
    Effect_4 |  .0163886    .003393   .0097385   .0230388      13620        361
    Effect_5 |  .0230699   .0038968   .0154322   .0307076      13462        361
    Effect_6 |  .0268285   .0042508   .0184972   .0351598      13253        361
    Effect_7 |  .0377147   .0044926   .0289095     .04652      13038        361
    Effect_8 |  .0392922   .0050394   .0294151   .0491694      12929        361
    Effect_9 |   .035109   .0055185   .0242929   .0459251      12840        361
   Effect_10 |  .0494016    .006029   .0375849   .0612182      12741        361
   Effect_11 |  .0518123   .0061055   .0398457   .0637788      12619        361
--------------------------------------------------------------------------------
Test of joint nullity of the effects : p-value = 0

  Av_tot_eff |  .3190721   .0406001   .2394973   .3986468      31470       3971
Average number of time periods over which a treatment's effect is accumulated = 11

   Placebo_1 | -.0055903   .0013173   -.008172  -.0030085      14154        361
   Placebo_2 | -.0083554   .0020689  -.0124104  -.0043003      13826        361
   Placebo_3 | -.0128183    .002977  -.0186532  -.0069834      13567        361
   Placebo_4 |  -.009143   .0033686  -.0157454  -.0025406      13302        361
   Placebo_5 | -.0075546   .0039816  -.0153585   .0002493      13005        361
   Placebo_6 | -.0073115   .0043748   -.015886    .001263      12682        361
   Placebo_7 | -.0079583   .0047566  -.0172812   .0013645      12431        361
   Placebo_8 |  -.008841   .0053184  -.0192648   .0015829      12214        361
   Placebo_9 | -.0143816   .0058363  -.0258204  -.0029427      11829        361
  Placebo_10 | -.0086498   .0061281  -.0206606   .0033611      10807        299
  Placebo_11 | -.0035924   .0066904  -.0167053   .0095206      10012        282
--------------------------------------------------------------------------------
Test of joint nullity of the placebos : p-value = 1.517e-06</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch09_fig1_hurricane_nocontrols.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9.1: Effects of Hurricane Hits on Government Transfers Per Capita (No Controls)</figcaption>
</figure>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("DIDmultiplegtDYN", "polars", "ggplot2"))</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtDYN)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(polars)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.RData"</span>))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>res_t2 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">df        =</span> df,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">outcome   =</span> <span class="st">"log_curr_trans_ind_gov_pc"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">group     =</span> <span class="st">"county_fips"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">time      =</span> <span class="st">"year"</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> <span class="st">"hurricane"</span>,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects   =</span> <span class="dv">11</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">placebo   =</span> <span class="dv">11</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster   =</span> <span class="st">"county_fips"</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(res_t2)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>res_t2<span class="sc">$</span>plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI    N      Switchers
Effect_1     0.01086  0.00162 0.00769  0.01403  14,240 361
Effect_2     0.01279  0.00237 0.00816  0.01743  13,953 361
Effect_3     0.01580  0.00301 0.00991  0.02170  13,766 361
Effect_4     0.01639  0.00339 0.00974  0.02304  13,620 361
Effect_5     0.02307  0.00390 0.01543  0.03071  13,462 361
Effect_6     0.02683  0.00425 0.01850  0.03516  13,253 361
Effect_7     0.03771  0.00449 0.02891  0.04652  13,038 361
Effect_8     0.03929  0.00504 0.02942  0.04917  12,929 361
Effect_9     0.03511  0.00552 0.02429  0.04593  12,840 361
Effect_10    0.04940  0.00603 0.03758  0.06122  12,741 361
Effect_11    0.05181  0.00611 0.03985  0.06378  12,619 361

Test of joint nullity of the effects  : p-value = 0.0000000

  Av_tot_eff |  0.31907  0.04060  0.23950  0.39865  31,470  3,971
Average number of time periods over which a treatment effect is accumulated: 11

Placebo_1    -0.00559 0.00132 -0.00817 -0.00301 14,154 361
Placebo_2    -0.00836 0.00207 -0.01241 -0.00430 13,826 361
Placebo_3    -0.01282 0.00298 -0.01865 -0.00698 13,567 361
Placebo_4    -0.00914 0.00337 -0.01575 -0.00254 13,302 361
Placebo_5    -0.00755 0.00398 -0.01536  0.00025 13,005 361
Placebo_6    -0.00731 0.00437 -0.01589  0.00126 12,682 361
Placebo_7    -0.00796 0.00476 -0.01728  0.00136 12,431 361
Placebo_8    -0.00884 0.00532 -0.01926  0.00158 12,214 361
Placebo_9    -0.01438 0.00584 -0.02582 -0.00294 11,829 361
Placebo_10   -0.00865 0.00613 -0.02066  0.00336 10,807 299
Placebo_11   -0.00359 0.00669 -0.01671  0.00952 10,012 282

Test of joint nullity of the placebos : p-value = 0.0000015</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch09_fig1_hurricane_nocontrols_R.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9.1: Effects of Hurricane Hits on Government Transfers Per Capita (No Controls)</figcaption>
</figure>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pip install py-did-multiplegt-dyn pandas pyarrow</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>matplotlib.use(<span class="st">'Agg'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> did_multiplegt_dyn <span class="im">import</span> DidMultiplegtDyn</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_parquet(<span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.parquet"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>res_t2 <span class="op">=</span> DidMultiplegtDyn(</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>pl.from_pandas(df),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    outcome<span class="op">=</span><span class="st">"log_curr_trans_ind_gov_pc"</span>, group<span class="op">=</span><span class="st">"county_fips"</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    time<span class="op">=</span><span class="st">"year"</span>, treatment<span class="op">=</span><span class="st">"hurricane"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    effects<span class="op">=</span><span class="dv">11</span>, placebo<span class="op">=</span><span class="dv">11</span>, cluster<span class="op">=</span><span class="st">"county_fips"</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>res_t2.fit()</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>res_t2.summary()</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>res_t2.plot()</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"ch09_fig1_hurricane_nocontrols_py.png"</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">"tight"</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>================================================================================
             Estimation of treatment effects: Event-study effects
================================================================================
               Block  Estimate       SE     LB CI     UB CI       N  Switchers
            Effect_1  0.010863 0.001617  0.007694  0.014032 14240.0      361.0
            Effect_2  0.012792 0.002365  0.008156  0.017427 13953.0      361.0
            Effect_3  0.015800 0.003007  0.009906  0.021695 13766.0      361.0
            Effect_4  0.016389 0.003393  0.009739  0.023039 13620.0      361.0
            Effect_5  0.023070 0.003897  0.015432  0.030708 13462.0      361.0
            Effect_6  0.026829 0.004251  0.018497  0.035160 13253.0      361.0
            Effect_7  0.037715 0.004493  0.028909  0.046520 13038.0      361.0
            Effect_8  0.039292 0.005039  0.029415  0.049169 12929.0      361.0
            Effect_9  0.035109 0.005519  0.024293  0.045925 12840.0      361.0
           Effect_10  0.049402 0.006029  0.037585  0.061218 12741.0      361.0
           Effect_11  0.051812 0.006105  0.039846  0.063779 12619.0      361.0
Average_Total_Effect  0.319072 0.040600  0.239497  0.398647 31470.0     3971.0
           Placebo_1 -0.005590 0.001317 -0.008172 -0.003008 14154.0      361.0
           Placebo_2 -0.008355 0.002069 -0.012410 -0.004300 13826.0      361.0
           Placebo_3 -0.012818 0.002977 -0.018653 -0.006983 13567.0      361.0
           Placebo_4 -0.009143 0.003369 -0.015745 -0.002541 13302.0      361.0
           Placebo_5 -0.007555 0.003982 -0.015359  0.000249 13005.0      361.0
           Placebo_6 -0.007312 0.004375 -0.015886  0.001263 12682.0      361.0
           Placebo_7 -0.007958 0.004757 -0.017281  0.001365 12431.0      361.0
           Placebo_8 -0.008841 0.005318 -0.019265  0.001583 12214.0      361.0
           Placebo_9 -0.014382 0.005836 -0.025820 -0.002943 11829.0      361.0
          Placebo_10 -0.008650 0.006128 -0.020661  0.003361 10807.0      299.0
          Placebo_11 -0.003592 0.006690 -0.016705  0.009521 10012.0      282.0
================================================================================
Test of joint nullity of the effects: p-value = 0.000000
Test of joint nullity of the placebos: p-value = 0.000002</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch09_fig1_hurricane_nocontrols_py.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9.1: Effects of Hurricane Hits on Government Transfers Per Capita (No Controls)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Effects are positive and increasing — hurricanes raise non-disaster transfers by ~1% in the short run and ~5% in the long run. The pre-trend test is highly significant (p ≈ 1.5e-06), suggesting a differential trend starting ~4 periods before treatment. The parallel-trends assumption is likely violated without controls.</p>
<hr>
</section>
<section id="t3-non-normalized-event-study-effects-with-county-level-controls" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="t3-non-normalized-event-study-effects-with-county-level-controls"><span class="header-section-number">1.3</span> T3: Non-Normalized Event-Study Effects (With County-Level Controls)</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>* <span class="kw">ssc</span> install did_multiplegt_dyn, <span class="kw">replace</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>copy <span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.dta"</span> <span class="st">"deryugina_2017.dta"</span>, <span class="kw">replace</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"deryugina_2017.dta"</span>, <span class="kw">clear</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="kw">local</span> vars coastal land_area1970 log_pop1969 frac_young1969 frac_old1969 frac_black1969 log_wage_pc1969 emp_rate1969</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="kw">local</span> controls</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="kw">foreach</span> v <span class="kw">of</span> <span class="kw">local</span> vars {</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">gen</span> <span class="ot">`v'</span>_year = <span class="ot">`v'</span> * <span class="fu">year</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">local</span> controls <span class="ot">`controls'</span> <span class="ot">`v'</span>_year</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn log_curr_trans_ind_gov_pc county_fips <span class="fu">year</span> hurricane, <span class="kw">effects</span>(11) placebo(11) <span class="kw">cluster</span>(county_fips) controls(<span class="ot">`controls'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>--------------------------------------------------------------------------------
             Estimation of treatment effects: Event-study effects
--------------------------------------------------------------------------------

             |  Estimate         SE      LB CI      UB CI          N  Switchers
-------------+------------------------------------------------------------------
    Effect_1 |  .0092419   .0015835   .0061383   .0123456      14077        361
    Effect_2 |  .0095925   .0022712   .0051409   .0140441      13794        361
    Effect_3 |  .0109771   .0028662   .0053594   .0165948      13609        361
    Effect_4 |  .0097365   .0032466   .0033733   .0160998      13464        361
    Effect_5 |  .0144296   .0037154   .0071476   .0217116      13305        361
    Effect_6 |  .0164425   .0040354   .0085333   .0243517      13097        361
    Effect_7 |  .0254598   .0042959   .0170399   .0338797      12884        361
    Effect_8 |  .0251647   .0048611   .0156371   .0346923      12775        361
    Effect_9 |  .0192179   .0053476   .0087368   .0296989      12685        361
   Effect_10 |   .031657   .0058645   .0201628   .0431512      12587        361
   Effect_11 |  .0317402   .0059652   .0200487   .0434317      12465        361
--------------------------------------------------------------------------------
Test of joint nullity of the effects : p-value = 0

  Av_tot_eff |  .2036597    .038535   .1281326   .2791869      31123       3971

   Placebo_1 | -.0039173   .0013091   -.006483  -.0013515      14000        361
   Placebo_2 | -.0051001   .0020352   -.009089  -.0011111      13679        361
   Placebo_3 | -.0077511   .0029252  -.0134844  -.0020179      13430        361
   Placebo_4 | -.0024941    .003301  -.0089639   .0039757      13181        361
   Placebo_5 |  .0011302     .00376  -.0062391   .0084996      12893        361
   Placebo_6 |   .003105   .0040325  -.0047987   .0110086      12577        361
   Placebo_7 |   .004438   .0043775  -.0041417   .0130177      12337        361
   Placebo_8 |  .0054782   .0048862  -.0040986   .0150551      12126        361
   Placebo_9 |  .0018036   .0052736  -.0085325   .0121397      11749        361
  Placebo_10 |  .0102888   .0056563  -.0007973   .0213749      10734        299
  Placebo_11 |  .0177286   .0060115   .0059462    .029511       9948        282
--------------------------------------------------------------------------------
Test of joint nullity of the placebos : p-value = 3.280e-07</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch09_fig2_hurricane_controls.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9.2: Effects of Hurricane Hits on Government Transfers Per Capita (With Controls)</figcaption>
</figure>
</div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("DIDmultiplegtDYN", "polars", "ggplot2"))</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtDYN)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(polars)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.RData"</span>))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"coastal"</span>, <span class="st">"land_area1970"</span>, <span class="st">"log_pop1969"</span>, <span class="st">"frac_young1969"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>          <span class="st">"frac_old1969"</span>, <span class="st">"frac_black1969"</span>, <span class="st">"log_wage_pc1969"</span>, <span class="st">"emp_rate1969"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (v <span class="cf">in</span> vars) df[[<span class="fu">paste0</span>(v, <span class="st">"_year"</span>)]] <span class="ot">&lt;-</span> df[[v]] <span class="sc">*</span> df<span class="sc">$</span>year</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>controls_list <span class="ot">&lt;-</span> <span class="fu">paste0</span>(vars, <span class="st">"_year"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>res_t3 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">df        =</span> df,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">outcome   =</span> <span class="st">"log_curr_trans_ind_gov_pc"</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">group     =</span> <span class="st">"county_fips"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">time      =</span> <span class="st">"year"</span>,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> <span class="st">"hurricane"</span>,</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects   =</span> <span class="dv">11</span>,</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">placebo   =</span> <span class="dv">11</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster   =</span> <span class="st">"county_fips"</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">controls  =</span> controls_list</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(res_t3)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>res_t3<span class="sc">$</span>plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI    N      Switchers
Effect_1     0.00924  0.00158 0.00614  0.01235  14,077 361
Effect_2     0.00959  0.00227 0.00514  0.01404  13,794 361
Effect_3     0.01098  0.00287 0.00536  0.01659  13,609 361
Effect_4     0.00974  0.00325 0.00337  0.01610  13,464 361
Effect_5     0.01443  0.00372 0.00715  0.02171  13,305 361
Effect_6     0.01644  0.00404 0.00853  0.02435  13,097 361
Effect_7     0.02546  0.00430 0.01704  0.03388  12,884 361
Effect_8     0.02517  0.00486 0.01564  0.03469  12,775 361
Effect_9     0.01922  0.00535 0.00874  0.02970  12,685 361
Effect_10    0.03166  0.00586 0.02016  0.04315  12,587 361
Effect_11    0.03174  0.00597 0.02005  0.04343  12,465 361

Test of joint nullity of the effects  : p-value = 0.0000

  Av_tot_eff |  0.20366  0.03853  0.12814  0.27919  31,123  3,971
Average number of time periods over which a treatment effect is accumulated: 11.0000

Placebo_1    -0.00392 0.00131 -0.00648 -0.00135 14,000 361
Placebo_2    -0.00510 0.00204 -0.00909 -0.00111 13,679 361
Placebo_3    -0.00775 0.00293 -0.01348 -0.00202 13,430 361
Placebo_4    -0.00249 0.00330 -0.00896  0.00398 13,181 361
Placebo_5     0.00113 0.00376 -0.00624  0.00850 12,893 361
Placebo_6     0.00310 0.00403 -0.00480  0.01101 12,577 361
Placebo_7     0.00444 0.00438 -0.00414  0.01302 12,337 361
Placebo_8     0.00548 0.00489 -0.00410  0.01505 12,126 361
Placebo_9     0.00180 0.00527 -0.00853  0.01214 11,749 361
Placebo_10    0.01029 0.00566 -0.00080  0.02137 10,734 299
Placebo_11    0.01773 0.00601  0.00595  0.02951  9,948 282

Test of joint nullity of the placebos : p-value = 0.0000</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch09_fig2_hurricane_controls_R.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9.2: Effects of Hurricane Hits on Government Transfers Per Capita (With Controls)</figcaption>
</figure>
</div>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pip install py-did-multiplegt-dyn pandas pyarrow</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>matplotlib.use(<span class="st">'Agg'</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> did_multiplegt_dyn <span class="im">import</span> DidMultiplegtDyn</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_parquet(<span class="st">"https://raw.githubusercontent.com/anzonyquispe/did_book/main/did_applied_book/data/deryugina_2017.parquet"</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>vars_list <span class="op">=</span> [<span class="st">"coastal"</span>, <span class="st">"land_area1970"</span>, <span class="st">"log_pop1969"</span>, <span class="st">"frac_young1969"</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>             <span class="st">"frac_old1969"</span>, <span class="st">"frac_black1969"</span>, <span class="st">"log_wage_pc1969"</span>, <span class="st">"emp_rate1969"</span>]</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> v <span class="kw">in</span> vars_list:</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    df[<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">}</span><span class="ss">_year"</span>] <span class="op">=</span> df[v] <span class="op">*</span> df[<span class="st">"year"</span>]</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>controls_list <span class="op">=</span> [<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">}</span><span class="ss">_year"</span> <span class="cf">for</span> v <span class="kw">in</span> vars_list]</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>res_t3 <span class="op">=</span> DidMultiplegtDyn(</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>pl.from_pandas(df),</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    outcome<span class="op">=</span><span class="st">"log_curr_trans_ind_gov_pc"</span>, group<span class="op">=</span><span class="st">"county_fips"</span>,</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    time<span class="op">=</span><span class="st">"year"</span>, treatment<span class="op">=</span><span class="st">"hurricane"</span>,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    effects<span class="op">=</span><span class="dv">11</span>, placebo<span class="op">=</span><span class="dv">11</span>, cluster<span class="op">=</span><span class="st">"county_fips"</span>,</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    controls<span class="op">=</span>controls_list</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>res_t3.fit()</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>res_t3.summary()</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>res_t3.plot()</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">"ch09_fig2_hurricane_controls_py.png"</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">"tight"</span>)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>================================================================================
             Estimation of treatment effects: Event-study effects
================================================================================
               Block  Estimate       SE     LB CI     UB CI       N  Switchers
            Effect_1  0.009242 0.001584  0.006138  0.012346 14077.0      361.0
            Effect_2  0.009593 0.002271  0.005141  0.014044 13794.0      361.0
            Effect_3  0.010977 0.002866  0.005360  0.016595 13609.0      361.0
            Effect_4  0.009737 0.003247  0.003374  0.016100 13464.0      361.0
            Effect_5  0.014430 0.003715  0.007148  0.021712 13305.0      361.0
            Effect_6  0.016443 0.004035  0.008534  0.024352 13097.0      361.0
            Effect_7  0.025460 0.004296  0.017040  0.033880 12884.0      361.0
            Effect_8  0.025165 0.004861  0.015638  0.034693 12775.0      361.0
            Effect_9  0.019219 0.005348  0.008738  0.029699 12685.0      361.0
           Effect_10  0.031658 0.005864  0.020163  0.043152 12587.0      361.0
           Effect_11  0.031741 0.005965  0.020050  0.043433 12465.0      361.0
Average_Total_Effect  0.203664 0.038535  0.128137  0.279191 31123.0     3971.0
           Placebo_1 -0.003917 0.001309 -0.006483 -0.001352 14000.0      361.0
           Placebo_2 -0.005100 0.002035 -0.009089 -0.001111 13679.0      361.0
           Placebo_3 -0.007752 0.002925 -0.013485 -0.002018 13430.0      361.0
           Placebo_4 -0.002494 0.003301 -0.008964  0.003975 13181.0      361.0
           Placebo_5  0.001130 0.003760 -0.006240  0.008499 12893.0      361.0
           Placebo_6  0.003104 0.004033 -0.004799  0.011008 12577.0      361.0
           Placebo_7  0.004437 0.004377 -0.004142  0.013017 12337.0      361.0
           Placebo_8  0.005478 0.004886 -0.004099  0.015054 12126.0      361.0
           Placebo_9  0.001803 0.005274 -0.008533  0.012139 11749.0      361.0
          Placebo_10  0.010288 0.005656 -0.000798  0.021374 10734.0      299.0
          Placebo_11  0.017728 0.006011  0.005946  0.029510  9948.0      282.0
================================================================================
Test of joint nullity of the effects: p-value = 0.000000
Test of joint nullity of the placebos: p-value = 0.000000</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch09_fig2_hurricane_controls_py.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9.2: Effects of Hurricane Hits on Government Transfers Per Capita (With Controls)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> After including controls, effects remain positive and significant (Av_tot_eff ≈ 0.204 vs.&nbsp;0.319 without controls). Pre-trends improve but the joint test remains significant (p ≈ 3.3e-07), suggesting a persistent differential trend even after conditioning on covariates.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch02.html" class="pagination-link" aria-label="Ch. 2 — East et al. (2023)">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ch. 2 — East et al.&nbsp;(2023)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>