project:
  type: book
  output-dir: docs

book:
  title: "Causal Inference with Differences-in-Differences: Credible Answers to Hard Questions"
  author: "Anzony Quispe Rojas"
  chapters:
    - index.qmd
    - chapters/ch03.qmd
    - chapters/ch04.qmd
    - chapters/ch05.qmd
    - chapters/ch06.qmd
    - chapters/ch07.qmd
    - chapters/ch08.qmd
  repo-url: https://github.com/Credible-Answers/did_book
  repo-actions: [edit, issue]
format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    code-tools: false
