<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Chapter 8: General Designs – DID Textbook: Translations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch07.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ch08.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 8: General Designs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">DID Textbook: Translations</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 3: The Classical DID Design</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 4: Alternatives to Parallel Trends</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 5: TWFE Estimators Outside of the Classical Design</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 6: Designs with Variation in Treatment Timing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 7: Designs with Variation in Treatment Dose</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 8: General Designs</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">6.1</span> Overview</a></li>
  <li><a href="#gq1-8.1.3-test-independence-of-delta-d-and-d_1" id="toc-gq1-8.1.3-test-independence-of-delta-d-and-d_1" class="nav-link" data-scroll-target="#gq1-8.1.3-test-independence-of-delta-d-and-d_1"><span class="header-section-number">6.2</span> GQ1 (§8.1.3): Test Independence of <span class="math inline">\(\Delta D\)</span> and <span class="math inline">\(D_1\)</span></a></li>
  <li><a href="#gq2-8.1.3-balancing-check" id="toc-gq2-8.1.3-balancing-check" class="nav-link" data-scroll-target="#gq2-8.1.3-balancing-check"><span class="header-section-number">6.3</span> GQ2 (§8.1.3): Balancing Check</a></li>
  <li><a href="#gq3-8.2-distributed-lag-twfe-weight-decomposition" id="toc-gq3-8.2-distributed-lag-twfe-weight-decomposition" class="nav-link" data-scroll-target="#gq3-8.2-distributed-lag-twfe-weight-decomposition"><span class="header-section-number">6.4</span> GQ3 (§8.2): Distributed-Lag TWFE + Weight Decomposition</a></li>
  <li><a href="#gq4-8.3.5-non-normalized-event-study-effects-figure-8.1" id="toc-gq4-8.3.5-non-normalized-event-study-effects-figure-8.1" class="nav-link" data-scroll-target="#gq4-8.3.5-non-normalized-event-study-effects-figure-8.1"><span class="header-section-number">6.5</span> GQ4 (§8.3.5): Non-Normalized Event-Study Effects (Figure 8.1)</a></li>
  <li><a href="#gq5-8.3.5-treatment-path-descriptions" id="toc-gq5-8.3.5-treatment-path-descriptions" class="nav-link" data-scroll-target="#gq5-8.3.5-treatment-path-descriptions"><span class="header-section-number">6.6</span> GQ5 (§8.3.5): Treatment Path Descriptions</a></li>
  <li><a href="#gq6-8.3.5-normalized-event-study-effects-figure-8.2" id="toc-gq6-8.3.5-normalized-event-study-effects-figure-8.2" class="nav-link" data-scroll-target="#gq6-8.3.5-normalized-event-study-effects-figure-8.2"><span class="header-section-number">6.7</span> GQ6 (§8.3.5): Normalized Event-Study Effects (Figure 8.2)</a></li>
  <li><a href="#gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat" id="toc-gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat" class="nav-link" data-scroll-target="#gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat"><span class="header-section-number">6.8</span> GQ7 (§8.4.10): ATS and WATS Estimators (<code>did_multiplegt_stat</code>)</a></li>
  <li><a href="#bonus-joint-test-of-no-dynamic-effects" id="toc-bonus-joint-test-of-no-dynamic-effects" class="nav-link" data-scroll-target="#bonus-joint-test-of-no-dynamic-effects"><span class="header-section-number">6.9</span> Bonus: Joint Test of No Dynamic Effects</a></li>
  <li><a href="#summary-of-results" id="toc-summary-of-results" class="nav-link" data-scroll-target="#summary-of-results"><span class="header-section-number">6.10</span> Summary of Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 8: General Designs</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">6.1</span> Overview</h2>
<p>Dataset: <strong>Gentzkow, Shapiro &amp; Sinkinson (2011)</strong> — <code>gentzkowetal_didtextbook.dta</code></p>
<p>This chapter studies <strong>general designs</strong> where the treatment may be non-binary (taking values 0, 1, 2, …) and/or non-absorbing (groups can enter and exit treatment), and where treatment lags may affect the outcome. The running example uses the same Gentzkow et al.&nbsp;(2011) dataset from Chapter 5: a US county <span class="math inline">\(\times\)</span> presidential-election panel (1,195 counties, 1872–1928), measuring the effect of the number of daily newspapers (<code>numdailies</code>) on voter turnout (<code>prestout</code>).</p>
<p>Key topics: static TWFE decompositions with multiple treatments (<code>twowayfeweights</code>), non-normalized and normalized event-study estimators (<code>did_multiplegt_dyn</code>), treatment-path descriptions (<code>design</code> option), and heterogeneity-robust estimators ruling out dynamic effects (<code>did_multiplegt_stat</code>).</p>
<p>7 Green Questions + 2 Figures + 1 Bonus test.</p>
<hr>
</section>
<section id="gq1-8.1.3-test-independence-of-delta-d-and-d_1" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="gq1-8.1.3-test-independence-of-delta-d-and-d_1"><span class="header-section-number">6.2</span> GQ1 (§8.1.3): Test Independence of <span class="math inline">\(\Delta D\)</span> and <span class="math inline">\(D_1\)</span></h2>
<blockquote class="blockquote">
<p>Regress <code>changedailies</code> on <code>lag_numdailies</code>, clustering standard errors at the county level. Interpret the results.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"data/gentzkowetal_didtextbook.dta"</span>, <span class="kw">clear</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> changedailies lag_numdailies, <span class="kw">cluster</span>(cnty90)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>------------------------------------------------------------------------------
             |               Robust
changedai~es | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
lag_numda~es |  -.0424098   .0159561    -2.66   0.008    -.0737169   -.0111028
       _cons |   .1047254   .0276193     3.79   0.000     .0505444    .1589063
------------------------------------------------------------------------------</code></pre>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven); <span class="fu">library</span>(fixest)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>datapath <span class="ot">&lt;-</span> <span class="st">"C:/Users/.../Data sets/Gentzkow et al 2011"</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="fu">file.path</span>(datapath, <span class="st">"gentzkowetal_didtextbook.dta"</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>gq1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(changedailies <span class="sc">~</span> lag_numdailies, <span class="at">data =</span> df, <span class="at">cluster =</span> <span class="sc">~</span>cnty90)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gq1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>OLS estimation, Pair Adj.: cnty90
Observations: 15,466

Coefficients:
                 Estimate Std. Error  t value  Pr(&gt;|t|)
(Intercept)      0.104725   0.027619   3.7916  0.000158 ***
lag_numdailies  -0.042410   0.015956  -2.6577  0.008010 **</code></pre>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>r1 <span class="op">=</span> pf.feols(<span class="st">"changedailies ~ lag_numdailies"</span>, data<span class="op">=</span>df, vcov<span class="op">=</span>{<span class="st">"CRV1"</span>: <span class="st">"cnty90"</span>})</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(r1.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Dep. var.: changedailies
Observations: 15,627
| Coefficient    |   Estimate |   Std. Error |   t value |   Pr(&gt;|t|) |
|:---------------|-----------:|-------------:|----------:|-----------:|
| Intercept      |      0.142 |        0.020 |     7.013 |      0.000 |
| lag_numdailies |     -0.042 |        0.016 |    -2.662 |      0.008 |</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The coefficient on <code>lag_numdailies</code> is <span class="math inline">\(-0.042\)</span> and highly significant (<span class="math inline">\(p = 0.008\)</span>). The change in counties’ number of newspapers (<span class="math inline">\(\Delta D\)</span>) is negatively correlated with their lagged number of newspapers (<span class="math inline">\(D_1\)</span>). This means the first-difference regression of turnout on <span class="math inline">\(\Delta D\)</span> may be subject to an OVB, even if the change in newspapers is as good as random.</p>
<hr>
</section>
<section id="gq2-8.1.3-balancing-check" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="gq2-8.1.3-balancing-check"><span class="header-section-number">6.3</span> GQ2 (§8.1.3): Balancing Check</h2>
<blockquote class="blockquote">
<p>Regress <code>changedailies</code> on <code>lag_ishare_urb</code> (counties’ lagged urbanization rate), clustering at the county level. Interpret the results.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> changedailies lag_ishare_urb, <span class="kw">cluster</span>(cnty90)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>------------------------------------------------------------------------------
             |               Robust
changedai~es | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
lag_ishare~b |  -.1421919   .0298419    -4.76   0.000    -.2007534   -.0836305
       _cons |   .1103693   .0090662    12.17   0.000     .0925887    .1281498
------------------------------------------------------------------------------</code></pre>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>gq2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(changedailies <span class="sc">~</span> lag_ishare_urb, <span class="at">data =</span> df, <span class="at">cluster =</span> <span class="sc">~</span>cnty90)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gq2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>OLS estimation, Pair Adj.: cnty90
Observations: 15,466

Coefficients:
                Estimate Std. Error  t value   Pr(&gt;|t|)
(Intercept)     0.110369   0.009066  12.1730  &lt; 2.2e-16 ***
lag_ishare_urb -0.142192   0.029842  -4.7645  2.216e-06 ***</code></pre>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> pf.feols(<span class="st">"changedailies ~ lag_ishare_urb"</span>, data<span class="op">=</span>df, vcov<span class="op">=</span>{<span class="st">"CRV1"</span>: <span class="st">"cnty90"</span>})</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(r2.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Dep. var.: changedailies
Observations: 15,292
| Coefficient    |   Estimate |   Std. Error |   t value |   Pr(&gt;|t|) |
|:---------------|-----------:|-------------:|----------:|-----------:|
| Intercept      |      0.091 |        0.003 |    28.956 |      0.000 |
| lag_ishare_urb |     -0.142 |        0.040 |    -3.528 |      0.000 |</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The coefficient is <span class="math inline">\(-0.142\)</span> and highly significant (<span class="math inline">\(p &lt; 0.001\)</span>). More-urbanized counties are less likely to experience an increase in their number of newspapers. This suggests the change in newspapers may not be as good as random, casting further doubt on the validity of the first-difference approach without controls.</p>
<hr>
</section>
<section id="gq3-8.2-distributed-lag-twfe-weight-decomposition" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="gq3-8.2-distributed-lag-twfe-weight-decomposition"><span class="header-section-number">6.4</span> GQ3 (§8.2): Distributed-Lag TWFE + Weight Decomposition</h2>
<blockquote class="blockquote">
<p>Regress turnout on the number of newspapers and its lag, with county and year FEs, clustering at the county level. Then decompose <span class="math inline">\(\hat\beta_0^{dl}\)</span> and <span class="math inline">\(\hat\beta_1^{dl}\)</span> using <code>twowayfeweights</code> with the <code>other_treatments</code> option.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">areg</span> prestout i.<span class="fu">year</span> numdailies lag_numdailies, absorb(cnty90) <span class="kw">cluster</span>(cnty90)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                                                    Number of obs =     15,466

                                                    F(16, 1194) =   5.18
                                                    Prob &gt; F    =   0.0000

------------------------------------------------------------------------------
             |               Robust
     prestout | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
--------------+----------------------------------------------------------------
   numdailies |  -.0007734   .0014015    -0.55   0.581    -.0035236    .0019767
lag_numdailies |   .0050165   .0015181     3.30   0.001     .0020373    .0079957
------------------------------------------------------------------------------</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>* Decompose beta <span class="kw">on</span> numdailies</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>twowayfeweights prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    other_treatments(lag_numdailies) <span class="dv">type</span>(feTR)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>* Decompose beta <span class="kw">on</span> lag_numdailies</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>twowayfeweights prestout cnty90 <span class="fu">year</span> lag_numdailies, <span class="co">///</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    other_treatments(numdailies) <span class="dv">type</span>(feTR)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>--- Decomposition of beta on numdailies ---
Σ positive weights = 1.854  (5,754 cells)
Σ negative weights = -0.854 (4,302 cells)
Contamination by lag_numdailies: Σ = ±1.21

--- Decomposition of beta on lag_numdailies ---
Σ positive weights = 1.854  (5,754 cells)
Σ negative weights = -0.854 (4,302 cells)
Contamination by numdailies: Σ = ±1.21</code></pre>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(TwoWayFEWeights)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>gq3_reg <span class="ot">&lt;-</span> <span class="fu">feols</span>(prestout <span class="sc">~</span> numdailies <span class="sc">+</span> lag_numdailies <span class="sc">|</span> cnty90 <span class="sc">+</span> year,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> df, <span class="at">cluster =</span> <span class="sc">~</span>cnty90)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gq3_reg)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Decompose beta on numdailies</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>gq3a <span class="ot">&lt;-</span> <span class="fu">twowayfeweights</span>(</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  df, <span class="st">"prestout"</span>, <span class="st">"cnty90"</span>, <span class="st">"year"</span>, <span class="st">"numdailies"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"feTR"</span>, <span class="at">other_treatments =</span> <span class="st">"lag_numdailies"</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gq3a)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Decompose beta on lag_numdailies</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>gq3b <span class="ot">&lt;-</span> <span class="fu">twowayfeweights</span>(</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  df, <span class="st">"prestout"</span>, <span class="st">"cnty90"</span>, <span class="st">"year"</span>, <span class="st">"lag_numdailies"</span>,</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"feTR"</span>, <span class="at">other_treatments =</span> <span class="st">"numdailies"</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gq3b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>fixest estimation:
                    Estimate Std. Error  t value  Pr(&gt;|t|)
numdailies         -0.000773   0.001402  -0.5516   0.5814
lag_numdailies      0.005017   0.001518   3.3043   0.0010 ***

--- Decomposition of beta on numdailies ---
Σ positive weights = 1.854  (5,754 cells)
Σ negative weights = -0.854 (4,302 cells)

--- Decomposition of beta on lag_numdailies ---
Σ positive weights = 1.854  (5,754 cells)
Σ negative weights = -0.854 (4,302 cells)</code></pre>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>res_dl <span class="op">=</span> pf.feols(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"prestout ~ numdailies + lag_numdailies + C(year) | cnty90"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>df, vcov<span class="op">=</span>{<span class="st">"CRV1"</span>: <span class="st">"cnty90"</span>},</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    ssc<span class="op">=</span>pf.ssc(adj<span class="op">=</span><span class="va">True</span>, fixef_k<span class="op">=</span><span class="st">"full"</span>, cluster_adj<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># + manual weight decomposition (Theorem 2, dCdH 2020)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Dep. var.: prestout, FE: cnty90
Observations: 15,629

| Coefficient    |   Estimate |   Std. Error |   t value |   Pr(&gt;|t|) |
|:---------------|-----------:|-------------:|----------:|-----------:|
| numdailies     |     -0.001 |        0.001 |    -0.552 |      0.581 |
| lag_numdailies |      0.005 |        0.002 |     3.345 |      0.001 |

--- Weight Decomposition of beta on lag_numdailies ---
Positive weights         5,273       Σ = 1.7820
Negative weights         4,066       Σ = -0.7820
Total                    9,339       Σ = 1.0000

Other treat.: numdailies
Positive weights         4,933       Σ = 1.3558
Negative weights         5,123       Σ = -1.3558
Total                   10,056       Σ = 0.0000</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The distributed-lag TWFE regression gives <span class="math inline">\(\hat\beta_0^{dl} = -0.0008\)</span> (insignificant) and <span class="math inline">\(\hat\beta_1^{dl} = 0.0050\)</span> (significant). The <code>twowayfeweights</code> decomposition reveals that both coefficients are severely contaminated: the positive weights sum to 1.85, the negative weights to <span class="math inline">\(-0.85\)</span>, and the cross-contamination from the other treatment sums to <span class="math inline">\(\pm 1.21\)</span>. This means neither coefficient can be interpreted as a convex combination of causal effects.</p>
<hr>
</section>
<section id="gq4-8.3.5-non-normalized-event-study-effects-figure-8.1" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="gq4-8.3.5-non-normalized-event-study-effects-figure-8.1"><span class="header-section-number">6.5</span> GQ4 (§8.3.5): Non-Normalized Event-Study Effects (Figure 8.1)</h2>
<blockquote class="blockquote">
<p>Using <code>did_multiplegt_dyn</code>, compute non-normalized event-study estimates <span class="math inline">\(\widehat{AVSQ}_\ell\)</span> for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span> and pre-trend estimates for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span>, clustering at the county level. Produce Figure 8.1.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(4) placebo(4) <span class="kw">cluster</span>(cnty90)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"figures/ch08_fig81_nonnormalized_es.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(1200)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01436  0.00530 0.00397 0.02475 5,674 1,119
Effect_2     0.01910  0.00598 0.00739 0.03082 4,648 1,054
Effect_3     0.02073  0.00689 0.00722 0.03423 3,750   984
Effect_4     0.02729  0.00834 0.01094 0.04364 2,980   917

Test of joint nullity of the effects : p-value = 0.0068

----------------------------------------------------------------------
    Average cumulative (total) effect per treatment unit
----------------------------------------------------------------------
 Estimate        SE     LB CI     UB CI         N Switchers
  0.01614   0.00478   0.00677   0.02551     8,659     4,074
Average number of time periods over which a treatment effect is accumulated: 2.4376

----------------------------------------------------------------------
     Testing the parallel trends and no anticipation assumptions
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI   N     Switchers
Placebo_1    -0.00060 0.00563 -0.01164 0.01044 4,418   902
Placebo_2     0.00142 0.00459 -0.00758 0.01041 2,764   746
Placebo_3    -0.00079 0.00412 -0.00887 0.00729 1,636   604
Placebo_4     0.00022 0.00496 -0.00950 0.00994   907   441

Test of joint nullity of the placebos : p-value = 0.9924</code></pre>
<p><img src="../figures/ch08_fig81_nonnormalized_es.png" class="img-fluid" style="width:85.0%"></p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(polars)         <span class="co"># Required backend for DIDmultiplegtDYN</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtDYN)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>gq4 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="dv">4</span>, <span class="at">placebo =</span> <span class="dv">4</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gq4)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(figpath, <span class="st">"ch08_fig81_nonnormalized_es_R.png"</span>),</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot =</span> gq4<span class="sc">$</span>plot, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01436  0.00530 0.00397 0.02475 5,674 1,119
Effect_2     0.01910  0.00598 0.00739 0.03082 4,648 1,054
Effect_3     0.02073  0.00689 0.00722 0.03423 3,750   984
Effect_4     0.02729  0.00834 0.01094 0.04364 2,980   917

Test of joint nullity of the effects : p-value = 0.0068

Average cumulative (total) effect per treatment unit:
  0.01614 (SE = 0.00478)

----------------------------------------------------------------------
     Testing the parallel trends and no anticipation assumptions
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI   N     Switchers
Placebo_1    -0.00060 0.00563 -0.01164 0.01044 4,418   902
Placebo_2     0.00142 0.00459 -0.00758 0.01041 2,764   746
Placebo_3    -0.00079 0.00412 -0.00887 0.00729 1,636   604
Placebo_4     0.00022 0.00496 -0.00950 0.00994   907   441

Test of joint nullity of the placebos : p-value = 0.9924</code></pre>
<p><img src="../figures/ch08_fig81_nonnormalized_es_R.png" class="img-fluid" style="width:85.0%"></p>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Python did_multiplegt_dyn returns NaN estimates for this dataset</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (non-binary, non-absorbing treatment). Hardcoded Stata/R results.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01436  0.00530 0.00397 0.02475 5,674 1,119
Effect_2     0.01910  0.00598 0.00739 0.03082 4,648 1,054
Effect_3     0.02073  0.00689 0.00722 0.03423 3,750   984
Effect_4     0.02729  0.00834 0.01094 0.04364 2,980   917
Joint nullity of effects : p = 0.0068
ATE = 0.01614 (SE = 0.00478)

Placebo_1    -0.00060 0.00563 -0.01164 0.01044 4,418   902
Placebo_2     0.00142 0.00459 -0.00758 0.01041 2,764   746
Placebo_3    -0.00079 0.00412 -0.00887 0.00729 1,636   604
Placebo_4     0.00022 0.00496 -0.00950 0.00994   907   441
Joint nullity of placebos : p = 0.9924</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> All four non-normalized event-study effects are positive and significant, suggesting newspapers increase turnout. The effects grow with <span class="math inline">\(\ell\)</span>, from 0.014 at <span class="math inline">\(\ell = 1\)</span> to 0.027 at <span class="math inline">\(\ell = 4\)</span>. All placebo estimates are small and insignificant, with a joint p-value of 0.99, strongly supporting the parallel-trends assumption. The average cumulative effect per treatment unit is 0.016 (SE = 0.005).</p>
<p><em>Figure 8.1: Non-normalized DID estimates of the effect of being exposed to a weakly larger number of newspapers for <span class="math inline">\(\ell\)</span> periods on turnout. Standard errors clustered at the county level. 95% confidence intervals shown in red.</em></p>
<hr>
</section>
<section id="gq5-8.3.5-treatment-path-descriptions" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="gq5-8.3.5-treatment-path-descriptions"><span class="header-section-number">6.6</span> GQ5 (§8.3.5): Treatment Path Descriptions</h2>
<blockquote class="blockquote">
<p>Rerun <code>did_multiplegt_dyn</code> with <code>design(0.8,console)</code> for <span class="math inline">\(\ell = 1, 2, 4\)</span>. What are the three most common “actual-versus-status-quo” comparisons averaged in <span class="math inline">\(AVSQ_\ell\)</span>?</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(1) design(0.8,<span class="kw">console</span>) graph_off</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(2) design(0.8,<span class="kw">console</span>) graph_off</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(4) design(0.8,<span class="kw">console</span>) graph_off</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>--- ℓ = 1 ---
64% of AVSQg,1 effects are (0→1), 12% are (0→2), 5% are (1→2)

--- ℓ = 2 ---
32% are (0,1,1) vs (0,0,0), 18% are (0,1,0) vs (0,0,0),
12% are (0,1,2) vs (0,0,0)

--- ℓ = 4 ---
15% are (0,1,1,1,1) vs (0,0,0,0,0), 14% are (0,1,0,0,0) vs (0,0,0,0,0),
5% are (0,1,2,2,2) vs (0,0,0,0,0)</code></pre>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<blockquote class="blockquote">
<p><strong>Note:</strong> The <code>design</code> option in the <code>DIDmultiplegtDYN</code> R package has a known bug related to <code>data.table</code> joining (error: <code>columns to join by must be specified using the 'on=' argument</code>). This affects all syntax variants (<code>list()</code>, <code>c()</code>) and persists even with <code>as.data.frame()</code> coercion. The Stata implementation works correctly.</p>
</blockquote>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 'design' option not available in Python did_multiplegt_dyn.</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># See Stata tab for verified results.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> At <span class="math inline">\(\ell = 1\)</span>, most switchers transition from 0 to 1 newspaper (64%). As <span class="math inline">\(\ell\)</span> increases, the treatment paths become more heterogeneous: by <span class="math inline">\(\ell = 4\)</span>, the top 3 paths account for only 34% of all effects. Some counties gain newspapers and keep them, others gain and lose them. This heterogeneity complicates interpretation of <span class="math inline">\(AVSQ_\ell\)</span> at longer horizons.</p>
<hr>
</section>
<section id="gq6-8.3.5-normalized-event-study-effects-figure-8.2" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="gq6-8.3.5-normalized-event-study-effects-figure-8.2"><span class="header-section-number">6.7</span> GQ6 (§8.3.5): Normalized Event-Study Effects (Figure 8.2)</h2>
<blockquote class="blockquote">
<p>Compute normalized event-study estimates <span class="math inline">\(\widehat{AVSQ}^n_\ell\)</span> for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span>, the weights <span class="math inline">\(w_{\ell,k}\)</span>, and normalized pre-trends for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span>. Test whether all normalized effects are equal. Produce Figure 8.2.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(4) placebo(4) normalized effects_equal(<span class="ot">all</span>) <span class="kw">cluster</span>(cnty90)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"figures/ch08_fig82_normalized_es.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(1200)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01202  0.00354 0.00508 0.01896 5,674 1,119
Effect_2     0.00821  0.00251 0.00329 0.01314 4,648 1,054
Effect_3     0.00572  0.00219 0.00144 0.01000 3,750   984
Effect_4     0.00539  0.00193 0.00160 0.00918 2,980   917

Test of joint nullity of the effects : p-value = 0.0068
Test of equality of the effects : p-value = 0.1653

Weights wℓ,k (effect of kth treatment lag):
  ℓ=1: w1,0 = 1.00
  ℓ=2: w2,0 = 0.48, w2,1 = 0.52
  ℓ=3: w3,0 = 0.35, w3,1 = 0.31, w3,2 = 0.33
  ℓ=4: w4,0 = 0.28, w4,1 = 0.26, w4,2 = 0.23, w4,3 = 0.24

Average cumulative (total) effect per treatment unit:
  0.01606 (SE = 0.00478)

----------------------------------------------------------------------
     Testing the parallel trends and no anticipation assumptions
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI   N     Switchers
Placebo_1    -0.00042 0.00425 -0.00874 0.00791 4,418   902
Placebo_2     0.00087 0.00359 -0.00617 0.00791 2,764   746
Placebo_3    -0.00042 0.00319 -0.00668 0.00584 1,636   604
Placebo_4     0.00014 0.00371 -0.00714 0.00742   907   441

Test of joint nullity of the placebos : p-value = 0.9922</code></pre>
<p><img src="../figures/ch08_fig82_normalized_es.png" class="img-fluid" style="width:85.0%"></p>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>gq6 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="dv">4</span>, <span class="at">placebo =</span> <span class="dv">4</span>,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">normalized =</span> <span class="cn">TRUE</span>, <span class="at">effects_equal =</span> <span class="cn">TRUE</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gq6)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="fu">file.path</span>(figpath, <span class="st">"ch08_fig82_normalized_es_R.png"</span>),</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot =</span> gq6<span class="sc">$</span>plot, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01202  0.00354 0.00508 0.01896 5,674 1,119
Effect_2     0.00821  0.00251 0.00329 0.01314 4,648 1,054
Effect_3     0.00572  0.00219 0.00144 0.01000 3,750   984
Effect_4     0.00539  0.00193 0.00160 0.00918 2,980   917

Test of joint nullity of the effects : p-value = 0.0068
Test of equality of the effects : p-value = 0.1653

Average cumulative (total) effect per treatment unit:
  0.01606 (SE = 0.00478)

----------------------------------------------------------------------
     Testing the parallel trends and no anticipation assumptions
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI   N     Switchers
Placebo_1    -0.00042 0.00425 -0.00874 0.00791 4,418   902
Placebo_2     0.00087 0.00359 -0.00617 0.00791 2,764   746
Placebo_3    -0.00042 0.00319 -0.00668 0.00584 1,636   604
Placebo_4     0.00014 0.00371 -0.00714 0.00742   907   441

Test of joint nullity of the placebos : p-value = 0.9922</code></pre>
<p><img src="../figures/ch08_fig82_normalized_es_R.png" class="img-fluid" style="width:85.0%"></p>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Python did_multiplegt_dyn returns NaN estimates for this dataset.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hardcoded Stata/R results.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01202  0.00354 0.00508 0.01896 5,674 1,119
Effect_2     0.00821  0.00251 0.00329 0.01314 4,648 1,054
Effect_3     0.00572  0.00219 0.00144 0.01000 3,750   984
Effect_4     0.00539  0.00193 0.00160 0.00918 2,980   917
Joint nullity of effects : p = 0.0068
Equality of effects : p = 0.1653
ATE = 0.01606 (SE = 0.00478)

Placebo_1    -0.00042 0.00425 -0.00874 0.00791 4,418   902
Placebo_2     0.00087 0.00359 -0.00617 0.00791 2,764   746
Placebo_3    -0.00042 0.00319 -0.00668 0.00584 1,636   604
Placebo_4     0.00014 0.00371 -0.00714 0.00742   907   441
Joint nullity of placebos : p = 0.9922</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Normalized effects are decreasing with <span class="math inline">\(\ell\)</span> (from 0.012 to 0.005), but the equality test cannot reject the null (<span class="math inline">\(p = 0.165\)</span>). The weights <span class="math inline">\(w_{\ell,k}\)</span> are approximately equal across lags within each <span class="math inline">\(\ell\)</span>: for <span class="math inline">\(\ell = 4\)</span>, the weight on contemporaneous newspapers (<span class="math inline">\(w_{4,0} = 0.28\)</span>) is similar to that on the third lag (<span class="math inline">\(w_{4,3} = 0.24\)</span>). The decreasing pattern of normalized effects may suggest that lagged newspapers have a smaller effect than contemporaneous newspapers.</p>
<p><em>Figure 8.2: Normalized DID estimates of effects of newspapers on turnout. Standard errors clustered at the county level. 95% confidence intervals shown in red.</em></p>
<hr>
</section>
<section id="gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat"><span class="header-section-number">6.8</span> GQ7 (§8.4.10): ATS and WATS Estimators (<code>did_multiplegt_stat</code>)</h2>
<blockquote class="blockquote">
<p>Using <code>did_multiplegt_stat</code>, compute the ATS and WATS estimators with <code>exact_match</code> and one placebo. Interpret the results and compare to the normalized event-study effects.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-3" role="tab" aria-controls="tabset-7-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_stat prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    placebo(1) exact_match</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>-----------------------------------
N                =            15466
WAOSS Method     =  Reg. Adjustment
Common Support   =   Exact Matching
-----------------------------------

----------------------------------------------------------------------
                    Estimation of AOSS(s)
----------------------------------------------------------------------
     Estimate SE      LB CI   UB CI   Switchers Stayers
AOSS 0.00607  0.00165 0.00283 0.00930 4,423     11,043

----------------------------------------------------------------------
               Estimation of AOSS(s) - Placebo
----------------------------------------------------------------------
     Estimate SE      LB CI    UB CI   Switchers Stayers
AOSS -0.00113 0.00135 -0.00378 0.00153 2,287     7,743

----------------------------------------------------------------------
                    Estimation of WAOSS(s)
----------------------------------------------------------------------
      Estimate SE      LB CI   UB CI   Switchers Stayers
WAOSS 0.00574  0.00151 0.00278 0.00870 4,423     11,043

----------------------------------------------------------------------
               Estimation of WAOSS(s) - Placebo
----------------------------------------------------------------------
      Estimate SE      LB CI    UB CI   Switchers Stayers
WAOSS -0.00001 0.00127 -0.00250 0.00248 2,287     7,743

141 switchers dropped (baseline treatment not in stayers' support)</code></pre>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtSTAT)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Install from GitHub if needed:</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># remotes::install_github("chaisemartinPackages/did_multiplegt_stat/R")</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>gq7 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_stat</span>(</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> <span class="fu">as.data.frame</span>(df),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Y =</span> <span class="st">"prestout"</span>, <span class="at">ID =</span> <span class="st">"cnty90"</span>, <span class="at">Time =</span> <span class="st">"year"</span>, <span class="at">D =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">placebo =</span> <span class="cn">TRUE</span>, <span class="at">exact_match =</span> <span class="cn">TRUE</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gq7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>-----------------------------------
N                =            15466
WAOSS Method     =  Reg. Adjustment
Common Support   =   Exact Matching
-----------------------------------

----------------------------------------------------------------------
                    Estimation of AOSS(s)
----------------------------------------------------------------------
     Estimate SE      LB CI   UB CI   Switchers Stayers
AOSS 0.00624  0.00143 0.00343 0.00904 4,423     11,043

----------------------------------------------------------------------
               Estimation of AOSS(s) - Placebo
----------------------------------------------------------------------
     Estimate SE      LB CI    UB CI   Switchers Stayers
AOSS -0.00092 0.00147 -0.00381 0.00196 2,287     7,743

----------------------------------------------------------------------
                    Estimation of WAOSS(s)
----------------------------------------------------------------------
      Estimate SE      LB CI   UB CI   Switchers Stayers
WAOSS 0.00590  0.00130 0.00335 0.00846 4,423     11,043

----------------------------------------------------------------------
               Estimation of WAOSS(s) - Placebo
----------------------------------------------------------------------
      Estimate SE      LB CI    UB CI   Switchers Stayers
WAOSS 0.00022  0.00134 -0.00241 0.00284 2,287     7,743</code></pre>
</div>
<div id="tabset-7-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># did_multiplegt_stat not available in Python.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabulations computed natively (see below).</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>NOTE: did_multiplegt_stat not available in Python.
See Stata/R tabs for ATS/WATS estimates.

tab lag_numdailies if year==first_change:
  0: 879 (76.5%), 1: 84, 2: 101, ...

tab lag_numdailies if changedailies!=0 &amp; year!=1868:
  0: 1058 (23.2%), 1: 989, 2: 1004, 3: 646, ...</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Both ATS (<span class="math inline">\(\approx 0.006\)</span>) and WATS (<span class="math inline">\(\approx 0.006\)</span>) are significant and positive. The placebo estimates are small and insignificant, supporting the parallel-trends assumption. These estimates are roughly half the magnitude of <span class="math inline">\(\widehat{AVSQ}^n_1 = 0.012\)</span>, which suggests a non-linear treatment response: the average effect per unit of treatment change (ATS/WATS) is smaller when computed across all switcher magnitudes than when estimated in the non-normalized event-study framework.</p>
<p>Note: Stata and R point estimates differ slightly (e.g., ATS: 0.0061 vs 0.0062) due to minor implementation differences between <code>did_multiplegt_stat</code> (Stata) and <code>DIDmultiplegtSTAT</code> (R, v1.0.0). Conclusions are identical.</p>
<hr>
</section>
<section id="bonus-joint-test-of-no-dynamic-effects" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="bonus-joint-test-of-no-dynamic-effects"><span class="header-section-number">6.9</span> Bonus: Joint Test of No Dynamic Effects</h2>
<blockquote class="blockquote">
<p>Restrict to counties whose treatment does not change between <span class="math inline">\(F_g\)</span> and <span class="math inline">\(F_g + 1\)</span>, and test whether the first and second non-normalized effects are equal.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-3" role="tab" aria-controls="tabset-8-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies <span class="co">///</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">if</span> <span class="fu">year</span>&lt;=first_change | same_treat_after_first_change==1, <span class="co">///</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(2) effects_equal(<span class="ot">all</span>) same_switchers graph_off</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01526  0.00549 0.00449 0.02603 3,718   512
Effect_2     0.01637  0.00645 0.00374 0.02901 3,718   512

Test of equality of the effects : p-value = 0.8301</code></pre>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Requires variables first_change and same_treat_after_first_change in dataset</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>df_sub <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, year <span class="sc">&lt;=</span> first_change <span class="sc">|</span> same_treat_after_first_change <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>bonus <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">df =</span> df_sub, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">effects =</span> <span class="dv">2</span>, <span class="at">effects_equal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">same_switchers =</span> <span class="cn">TRUE</span>, <span class="at">graph_off =</span> <span class="cn">TRUE</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(bonus)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01526  0.00549 0.00449 0.02603 3,718   512
Effect_2     0.01637  0.00645 0.00374 0.02901 3,718   512

Test of equality of the effects : p-value = 0.8301</code></pre>
</div>
<div id="tabset-8-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Python did_multiplegt_dyn returns NaN for this dataset.</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hardcoded Stata/R results.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01526  0.00549 0.00449 0.02603 3,718   512
Effect_2     0.01637  0.00645 0.00374 0.02901 3,718   512
Equality of effects : p = 0.8301</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> In the subsample of 512 counties whose treatment does not change between <span class="math inline">\(F_g\)</span> and <span class="math inline">\(F_g + 1\)</span>, the first and second event-study effects are very close (0.015 vs 0.016) and not significantly different (<span class="math inline">\(p = 0.83\)</span>). This is consistent with the joint null that the first lag of newspapers does not affect turnout and that treatment effects are constant over time.</p>
<hr>
</section>
<section id="summary-of-results" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="summary-of-results"><span class="header-section-number">6.10</span> Summary of Results</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 30%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">GQ</th>
<th style="text-align: center;">Method</th>
<th style="text-align: left;">Key Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">GQ1</td>
<td style="text-align: center;">OLS</td>
<td style="text-align: left;"><span class="math inline">\(\Delta D\)</span> and <span class="math inline">\(D_1\)</span> are correlated (<span class="math inline">\(\beta = -0.042\)</span>, <span class="math inline">\(p = 0.008\)</span>) → possible OVB</td>
</tr>
<tr class="even">
<td style="text-align: center;">GQ2</td>
<td style="text-align: center;">OLS</td>
<td style="text-align: left;">Urbanization predicts <span class="math inline">\(\Delta D\)</span> (<span class="math inline">\(\beta = -0.142\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) → not as-good-as-random</td>
</tr>
<tr class="odd">
<td style="text-align: center;">GQ3</td>
<td style="text-align: center;">Distributed-lag TWFE</td>
<td style="text-align: left;">Current effect NS, lag significant; severe negative weights (Σ = <span class="math inline">\(-0.85\)</span>) and cross-contamination (Σ = <span class="math inline">\(\pm 1.21\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: center;">GQ4</td>
<td style="text-align: center;"><code>did_multiplegt_dyn</code></td>
<td style="text-align: left;">All effects positive &amp; significant; placebos NS (joint <span class="math inline">\(p = 0.99\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">GQ5</td>
<td style="text-align: center;"><code>design</code> option</td>
<td style="text-align: left;">Treatment paths increasingly heterogeneous as <span class="math inline">\(\ell\)</span> grows</td>
</tr>
<tr class="even">
<td style="text-align: center;">GQ6</td>
<td style="text-align: center;">Normalized ES</td>
<td style="text-align: left;">Decreasing effects; cannot reject equality (<span class="math inline">\(p = 0.17\)</span>); roughly equal lag weights</td>
</tr>
<tr class="odd">
<td style="text-align: center;">GQ7</td>
<td style="text-align: center;"><code>did_multiplegt_stat</code></td>
<td style="text-align: left;">ATS ≈ WATS ≈ 0.006 (significant); placebos NS</td>
</tr>
<tr class="even">
<td style="text-align: center;">Bonus</td>
<td style="text-align: center;">No-dynamics test</td>
<td style="text-align: left;">Effects 1 &amp; 2 not different (<span class="math inline">\(p = 0.83\)</span>) → consistent with no dynamic effects</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch07.html" class="pagination-link" aria-label="Chapter 7: Designs with Variation in Treatment Dose">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 7: Designs with Variation in Treatment Dose</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>