<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Chapter 8: General Designs – DID Textbook: Translations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch07.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ch08.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 8: General Designs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">DID Textbook: Translations</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Chapter 3: The Classical DID Design</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 4: Alternatives to Parallel Trends</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 5: TWFE Estimators Outside of the Classical Design</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 6: Designs with Variation in Treatment Timing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 7: Designs with Variation in Treatment Dose</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 8: General Designs</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">6.1</span> Overview</a></li>
  <li><a href="#panelview" id="toc-panelview" class="nav-link" data-scroll-target="#panelview"><span class="header-section-number">6.2</span> PanelView</a></li>
  <li><a href="#gq1-8.1.3-test-independence-of-delta-d-and-d_1" id="toc-gq1-8.1.3-test-independence-of-delta-d-and-d_1" class="nav-link" data-scroll-target="#gq1-8.1.3-test-independence-of-delta-d-and-d_1"><span class="header-section-number">6.3</span> GQ1 (§8.1.3): Test Independence of <span class="math inline">\(\Delta D\)</span> and <span class="math inline">\(D_1\)</span></a></li>
  <li><a href="#gq2-8.1.3-balancing-check" id="toc-gq2-8.1.3-balancing-check" class="nav-link" data-scroll-target="#gq2-8.1.3-balancing-check"><span class="header-section-number">6.4</span> GQ2 (§8.1.3): Balancing Check</a></li>
  <li><a href="#gq3-8.2-distributed-lag-twfe-weight-decomposition" id="toc-gq3-8.2-distributed-lag-twfe-weight-decomposition" class="nav-link" data-scroll-target="#gq3-8.2-distributed-lag-twfe-weight-decomposition"><span class="header-section-number">6.5</span> GQ3 (§8.2): Distributed-Lag TWFE + Weight Decomposition</a></li>
  <li><a href="#gq4-8.3.5-non-normalized-event-study-effects-figure-8.1" id="toc-gq4-8.3.5-non-normalized-event-study-effects-figure-8.1" class="nav-link" data-scroll-target="#gq4-8.3.5-non-normalized-event-study-effects-figure-8.1"><span class="header-section-number">6.6</span> GQ4 (§8.3.5): Non-Normalized Event-Study Effects (Figure 8.1)</a></li>
  <li><a href="#gq5-8.3.5-treatment-path-descriptions" id="toc-gq5-8.3.5-treatment-path-descriptions" class="nav-link" data-scroll-target="#gq5-8.3.5-treatment-path-descriptions"><span class="header-section-number">6.7</span> GQ5 (§8.3.5): Treatment Path Descriptions</a></li>
  <li><a href="#gq6-8.3.5-normalized-event-study-effects-figure-8.2" id="toc-gq6-8.3.5-normalized-event-study-effects-figure-8.2" class="nav-link" data-scroll-target="#gq6-8.3.5-normalized-event-study-effects-figure-8.2"><span class="header-section-number">6.8</span> GQ6 (§8.3.5): Normalized Event-Study Effects (Figure 8.2)</a></li>
  <li><a href="#gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat" id="toc-gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat" class="nav-link" data-scroll-target="#gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat"><span class="header-section-number">6.9</span> GQ7 (§8.4.10): ATS and WATS Estimators (<code>did_multiplegt_stat</code>)</a></li>
  <li><a href="#bonus-joint-test-of-no-dynamic-effects" id="toc-bonus-joint-test-of-no-dynamic-effects" class="nav-link" data-scroll-target="#bonus-joint-test-of-no-dynamic-effects"><span class="header-section-number">6.10</span> Bonus: Joint Test of No Dynamic Effects</a></li>
  <li><a href="#summary-of-results" id="toc-summary-of-results" class="nav-link" data-scroll-target="#summary-of-results"><span class="header-section-number">6.11</span> Summary of Results</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 8: General Designs</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">6.1</span> Overview</h2>
<p>Dataset: <strong>Gentzkow, Shapiro &amp; Sinkinson (2011)</strong> — <code>gentzkowetal_didtextbook.dta</code> (16,872 observations, 1,195 counties, 16 election years 1868–1928)</p>
<p>This chapter studies <strong>general designs</strong> where the treatment may be non-binary (taking values 0, 1, 2, …) and/or non-absorbing (groups can enter and exit treatment), and where treatment lags may affect the outcome. The running example measures the effect of the number of daily newspapers (<code>numdailies</code>) on presidential voter turnout (<code>prestout</code>).</p>
<p>Key topics: static TWFE decompositions with multiple treatments (<code>twowayfeweights</code>), non-normalized and normalized event-study estimators (<code>did_multiplegt_dyn</code>), treatment-path descriptions (<code>design</code> option), and heterogeneity-robust estimators ruling out dynamic effects (<code>did_multiplegt_stat</code>).</p>
<p>7 Green Questions + 2 Figures + 1 Bonus test.</p>
<p><strong>Packages used:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 29%">
<col style="width: 12%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Task</th>
<th>Stata</th>
<th>R</th>
<th>Python</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>PanelView</td>
<td><code>panelview</code> (SSC)</td>
<td><code>panelView</code> (CRAN)</td>
<td><code>matplotlib</code> (manual)</td>
</tr>
<tr class="even">
<td>OLS / TWFE</td>
<td><code>reg</code>, <code>areg</code></td>
<td><code>fixest</code>, <code>sandwich</code></td>
<td><code>statsmodels</code></td>
</tr>
<tr class="odd">
<td>Weight decomposition</td>
<td><code>twowayfeweights</code> (SSC)</td>
<td><code>TwoWayFEWeights</code> (CRAN)</td>
<td>Not available (<code>other_treatments</code>)</td>
</tr>
<tr class="even">
<td>Event-study DID</td>
<td><code>did_multiplegt_dyn</code> (SSC)</td>
<td><code>DIDmultiplegtDYN</code> (CRAN)</td>
<td><code>py-did-multiplegt-dyn</code> (PyPI)</td>
</tr>
<tr class="odd">
<td>Static DID (ATS/WATS)</td>
<td><code>did_multiplegt_stat</code> (SSC)</td>
<td><code>DIDmultiplegtSTAT</code> (GitHub)</td>
<td><code>py_did_multiplegt_stat</code> (local)</td>
</tr>
</tbody>
</table>
<p><strong>Installation notes:</strong></p>
<ul>
<li><strong>R <code>DIDmultiplegtSTAT</code>:</strong> <code>devtools::install_github("chaisemartinPackages/did_multiplegt_stat/R", force = TRUE)</code></li>
<li><strong>R <code>DIDmultiplegtDYN</code>:</strong> The <code>design()</code> option has a known <code>data.table</code> join bug. Treatment path tables (GQ5) are Stata-only. Effects match across platforms.</li>
<li><strong>Python <code>did_multiplegt_dyn</code>:</strong> <code>pip install py-did-multiplegt-dyn</code>. Requires <code>polars</code> DataFrames. Point estimates return NaN in v0.1.4 (SE and N/Switchers are correct).</li>
<li><strong>Python <code>did_multiplegt_stat</code>:</strong> Local notebook-based translation; see <code>py_did_multiplegt_stat</code>.</li>
</ul>
<p><strong>Note on cross-platform differences:</strong> GQ1–GQ4 and GQ6 match exactly between Stata and R to 7 decimals. GQ7 (<code>did_multiplegt_stat</code>) shows small differences between Stata, R, and Python due to internal implementation variations. N, switchers, and stayers counts are identical across all three.</p>
<hr>
</section>
<section id="panelview" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="panelview"><span class="header-section-number">6.2</span> PanelView</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>panelview prestout numdailies, i(cnty90) t(<span class="fu">year</span>) <span class="dv">type</span>(treat) <span class="co">///</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="bn">title</span>(<span class="st">"Treatment Status: Gentzkow et al. (2011)"</span>) <span class="bn">legend</span>(<span class="kw">off</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"$FIGDIR\ch08_panelview_stata.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(1200)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_panelview_stata.png" class="img-fluid figure-img"></p>
<figcaption>Stata PanelView</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(panelView)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">panelview</span>(prestout <span class="sc">~</span> numdailies, <span class="at">data =</span> df,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"cnty90"</span>, <span class="st">"year"</span>), <span class="at">type =</span> <span class="st">"treat"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">"Treatment Status: Gentzkow et al. (2011)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_panelview_R.png" class="img-fluid figure-img"></p>
<figcaption>R PanelView</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pv <span class="op">=</span> df.pivot_table(index<span class="op">=</span><span class="st">'cnty90'</span>, columns<span class="op">=</span><span class="st">'year'</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                    values<span class="op">=</span><span class="st">'numdailies'</span>, aggfunc<span class="op">=</span><span class="st">'first'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>pv_sorted <span class="op">=</span> pv.loc[pv.mean(axis<span class="op">=</span><span class="dv">1</span>).sort_values(ascending<span class="op">=</span><span class="va">True</span>).index]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Heatmap with Blues colormap, sorted by mean treatment intensity</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_panelview_Python.png" class="img-fluid figure-img"></p>
<figcaption>Python PanelView</figcaption>
</figure>
</div>
</div>
</div>
</div>
<hr>
</section>
<section id="gq1-8.1.3-test-independence-of-delta-d-and-d_1" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="gq1-8.1.3-test-independence-of-delta-d-and-d_1"><span class="header-section-number">6.3</span> GQ1 (§8.1.3): Test Independence of <span class="math inline">\(\Delta D\)</span> and <span class="math inline">\(D_1\)</span></h2>
<blockquote class="blockquote">
<p>Regress <code>changedailies</code> on <code>lag_numdailies</code>, clustering standard errors at the county level.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> changedailies lag_numdailies, <span class="kw">cluster</span>(cnty90)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                               (Std. err. adjusted for 1,195 clusters in cnty90)
--------------------------------------------------------------------------------
               |               Robust
 changedailies | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
---------------+----------------------------------------------------------------
lag_numdailies |  -.0419532   .0157613    -2.66   0.008    -.0728841   -.0110222
         _cons |   .1419944   .0202459     7.01   0.000     .1022647    .1817241
--------------------------------------------------------------------------------
N = 15,627</code></pre>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest); <span class="fu">library</span>(sandwich)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>gq1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(changedailies <span class="sc">~</span> lag_numdailies, <span class="at">data =</span> df)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(gq1, <span class="at">vcov =</span> <span class="fu">vcovCL</span>(gq1, <span class="at">cluster =</span> <span class="sc">~</span>cnty90))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                 Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)     0.1419944  0.0202459  7.0135   0.0000
lag_numdailies -0.0419532  0.0157613 -2.6618   0.0078
N = 15,627</code></pre>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'changedailies'</span>,<span class="st">'lag_numdailies'</span>])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> sub[<span class="st">'changedailies'</span>]<span class="op">;</span> X <span class="op">=</span> sm.add_constant(sub[<span class="st">'lag_numdailies'</span>])</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> sm.OLS(y, X).fit(cov_type<span class="op">=</span><span class="st">'cluster'</span>, cov_kwds<span class="op">=</span>{<span class="st">'groups'</span>: sub[<span class="st">'cnty90'</span>]})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>  Variable                          Coef      Std.Err          t      P&gt;|t|
  const                        0.1419944    0.0202459      7.013     0.0000
  lag_numdailies              -0.0419532    0.0157613     -2.662     0.0078
  N = 15,627</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The coefficient on <code>lag_numdailies</code> is <span class="math inline">\(-0.0419532\)</span> and highly significant (<span class="math inline">\(p = 0.008\)</span>). The change in counties’ number of newspapers (<span class="math inline">\(\Delta D\)</span>) is negatively correlated with their lagged number of newspapers (<span class="math inline">\(D_1\)</span>). This means the first-difference regression of turnout on <span class="math inline">\(\Delta D\)</span> may be subject to an OVB, even if the change in newspapers is as good as random.</p>
<hr>
</section>
<section id="gq2-8.1.3-balancing-check" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="gq2-8.1.3-balancing-check"><span class="header-section-number">6.4</span> GQ2 (§8.1.3): Balancing Check</h2>
<blockquote class="blockquote">
<p>Regress <code>changedailies</code> on <code>lag_ishare_urb</code> (counties’ lagged urbanization rate), clustering at the county level.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> changedailies lag_ishare_urb, <span class="kw">cluster</span>(cnty90)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                               (Std. err. adjusted for 1,195 clusters in cnty90)
--------------------------------------------------------------------------------
               |               Robust
 changedailies | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
---------------+----------------------------------------------------------------
lag_ishare_urb |  -.1422166   .0403066    -3.53   0.000    -.2213139   -.0631193
         _cons |   .0906335   .0031300    28.96   0.000     .0844918    .0967752
--------------------------------------------------------------------------------
N = 15,292</code></pre>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>gq2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(changedailies <span class="sc">~</span> lag_ishare_urb, <span class="at">data =</span> df)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(gq2, <span class="at">vcov =</span> <span class="fu">vcovCL</span>(gq2, <span class="at">cluster =</span> <span class="sc">~</span>cnty90))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                Estimate Std. Error t value  Pr(&gt;|t|)
(Intercept)    0.0906335  0.0031300 28.9564    0.0000
lag_ishare_urb -0.1422166  0.0403066 -3.5284   0.0004
N = 15,292</code></pre>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'changedailies'</span>,<span class="st">'lag_ishare_urb'</span>])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> sub[<span class="st">'changedailies'</span>]<span class="op">;</span> X <span class="op">=</span> sm.add_constant(sub[<span class="st">'lag_ishare_urb'</span>])</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> sm.OLS(y, X).fit(cov_type<span class="op">=</span><span class="st">'cluster'</span>, cov_kwds<span class="op">=</span>{<span class="st">'groups'</span>: sub[<span class="st">'cnty90'</span>]})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>  Variable                          Coef      Std.Err          t      P&gt;|t|
  const                        0.0906335    0.0031300     28.956     0.0000
  lag_ishare_urb              -0.1422166    0.0403066     -3.528     0.0004
  N = 15,292</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The coefficient is <span class="math inline">\(-0.1422166\)</span> and highly significant (<span class="math inline">\(p &lt; 0.001\)</span>). More-urbanized counties are less likely to experience an increase in their number of newspapers. This suggests the change in newspapers may not be as good as random, casting further doubt on the validity of the first-difference approach without controls.</p>
<hr>
</section>
<section id="gq3-8.2-distributed-lag-twfe-weight-decomposition" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="gq3-8.2-distributed-lag-twfe-weight-decomposition"><span class="header-section-number">6.5</span> GQ3 (§8.2): Distributed-Lag TWFE + Weight Decomposition</h2>
<blockquote class="blockquote">
<p>Regress turnout on the number of newspapers and its lag, with county and year FEs, clustering at the county level. Then decompose <span class="math inline">\(\hat\beta_0^{dl}\)</span> and <span class="math inline">\(\hat\beta_1^{dl}\)</span> using <code>twowayfeweights</code> with the <code>other_treatments</code> option.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-3" role="tab" aria-controls="tabset-4-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">areg</span> prestout i.<span class="fu">year</span> numdailies lag_numdailies, absorb(cnty90) <span class="kw">cluster</span>(cnty90)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                               (Std. err. adjusted for 1,195 clusters in cnty90)
--------------------------------------------------------------------------------
               |               Robust
       prestout | Coefficient  std. err.      t    P&gt;|t|     [95% conf. interval]
----------------+----------------------------------------------------------------
    numdailies  |  -.0007962   .0014419    -0.55   0.581    -.0036257    .0020333
 lag_numdailies |   .0050348   .0015052     3.34   0.001     .0020814    .0079882
--------------------------------------------------------------------------------
N = 15,629</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>* Decompose beta <span class="kw">on</span> numdailies</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>twowayfeweights prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    other_treatments(lag_numdailies) <span class="dv">type</span>(feTR)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>* Decompose beta <span class="kw">on</span> lag_numdailies</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>twowayfeweights prestout cnty90 <span class="fu">year</span> lag_numdailies, <span class="co">///</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    other_treatments(numdailies) <span class="dv">type</span>(feTR)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>--- Decomposition of beta on numdailies (β = -0.0008) ---
Under the common trends assumption, beta estimates a weighted sum of 10,056 ATTs.
 5,754 ATTs receive a positive weight, and 4,302 receive a negative weight.
 Σ positive weights = 1.8541  |  Σ negative weights = -0.8541
 Other treatment (lag_numdailies):
   4,721 positive (Σ = 1.2137) | 4,618 negative (Σ = -1.2137)

--- Decomposition of beta on lag_numdailies (β = 0.0050) ---
Under the common trends assumption, beta estimates a weighted sum of 9,339 ATTs.
 5,273 ATTs receive a positive weight, and 4,066 receive a negative weight.
 Σ positive weights = 1.7820  |  Σ negative weights = -0.7820
 Other treatment (numdailies):
   4,933 positive (Σ = 1.3558) | 5,123 negative (Σ = -1.3558)</code></pre>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest); <span class="fu">library</span>(TwoWayFEWeights)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>gq3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(prestout <span class="sc">~</span> numdailies <span class="sc">+</span> lag_numdailies <span class="sc">|</span> cnty90 <span class="sc">+</span> year,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> df, <span class="at">cluster =</span> <span class="sc">~</span>cnty90)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gq3)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>gq3a <span class="ot">&lt;-</span> <span class="fu">twowayfeweights</span>(df, <span class="st">"prestout"</span>, <span class="st">"cnty90"</span>, <span class="st">"year"</span>, <span class="st">"numdailies"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type =</span> <span class="st">"feTR"</span>, <span class="at">other_treatments =</span> <span class="st">"lag_numdailies"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>gq3b <span class="ot">&lt;-</span> <span class="fu">twowayfeweights</span>(df, <span class="st">"prestout"</span>, <span class="st">"cnty90"</span>, <span class="st">"year"</span>, <span class="st">"lag_numdailies"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type =</span> <span class="st">"feTR"</span>, <span class="at">other_treatments =</span> <span class="st">"numdailies"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                 Estimate Std. Error  t value Pr(&gt;|t|)
numdailies     -0.0007962  0.0013864 -0.5743   0.5658
lag_numdailies  0.0050348  0.0014472  3.4790   0.0005
N = 15,629

--- Decomposition of beta on numdailies (β = -0.0008) ---
 Σ positive weights = 1.8541 (5,754 ATTs)
 Σ negative weights = -0.8541 (4,302 ATTs)
 Other treatment: 4,721 pos (Σ = 1.2137) | 4,618 neg (Σ = -1.2137)

--- Decomposition of beta on lag_numdailies (β = 0.0050) ---
 Σ positive weights = 1.7820 (5,273 ATTs)
 Σ negative weights = -0.7820 (4,066 ATTs)
 Other treatment: 4,933 pos (Σ = 1.3558) | 5,123 neg (Σ = -1.3558)</code></pre>
</div>
<div id="tabset-4-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TWFE via iterative demeaning (Frisch-Waugh-Lovell, 50 iterations)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">'prestout'</span>,<span class="st">'numdailies'</span>,<span class="st">'lag_numdailies'</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> df.dropna(subset<span class="op">=</span>cols).copy()</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>dem <span class="op">=</span> sub[cols].copy()</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">50</span>):</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> v <span class="kw">in</span> cols:</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>        dem[v] <span class="op">-=</span> dem.groupby(sub[<span class="st">'cnty90'</span>])[v].transform(<span class="st">'mean'</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>        dem[v] <span class="op">-=</span> dem.groupby(sub[<span class="st">'year'</span>])[v].transform(<span class="st">'mean'</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> sm.OLS(dem[<span class="st">'prestout'</span>], dem[[<span class="st">'numdailies'</span>,<span class="st">'lag_numdailies'</span>]]).fit(</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    cov_type<span class="op">=</span><span class="st">'cluster'</span>, cov_kwds<span class="op">=</span>{<span class="st">'groups'</span>: sub[<span class="st">'cnty90'</span>]})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>  Variable                          Coef      Std.Err          t      P&gt;|t|
  numdailies                  -0.0007962    0.0013850     -0.575     0.5654
  lag_numdailies               0.0050348    0.0014458      3.482     0.0005
  N = 15,629

  twowayfeweights with other_treatments not available in Python.
  See Stata/R tabs for weight decomposition.</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> The distributed-lag TWFE regression gives <span class="math inline">\(\hat\beta_0^{dl} = -0.0007962\)</span> (insignificant) and <span class="math inline">\(\hat\beta_1^{dl} = 0.0050348\)</span> (significant). The <code>twowayfeweights</code> decomposition reveals that both coefficients are severely contaminated: the positive weights sum to 1.85, the negative weights to <span class="math inline">\(-0.85\)</span>, and the cross-contamination from the other treatment sums to <span class="math inline">\(\pm 1.21\)</span>. This means neither coefficient can be interpreted as a convex combination of causal effects.</p>
<hr>
</section>
<section id="gq4-8.3.5-non-normalized-event-study-effects-figure-8.1" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="gq4-8.3.5-non-normalized-event-study-effects-figure-8.1"><span class="header-section-number">6.6</span> GQ4 (§8.3.5): Non-Normalized Event-Study Effects (Figure 8.1)</h2>
<blockquote class="blockquote">
<p>Using <code>did_multiplegt_dyn</code>, compute non-normalized event-study estimates <span class="math inline">\(\widehat{AVSQ}_\ell\)</span> for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span> and pre-trend estimates for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span>, clustering at the county level. Produce Figure 8.1.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-3" role="tab" aria-controls="tabset-5-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(4) placebo(4) <span class="kw">cluster</span>(cnty90)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"$FIGDIR\ch08_fig81_nonnormalized_es.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(1200)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.0144244 0.0042477 0.0060990 0.0227498 5,674 1,119
Effect_2     0.0190899 0.0058429 0.0076380 0.0305418 4,648 1,054
Effect_3     0.0207147 0.0079164 0.0051987 0.0362307 3,750   984
Effect_4     0.0272653 0.0097924 0.0080724 0.0464582 2,980   917

Test of joint nullity of the effects : p-value = 0.0068

----------------------------------------------------------------------
    Average cumulative (total) effect per treatment unit
----------------------------------------------------------------------
 Estimate        SE     LB CI     UB CI         N Switchers
  0.0160565   0.0047761   0.0067156   0.0253974     8,659     4,074
Average number of periods over which effect is accumulated: 2.4376

----------------------------------------------------------------------
     Testing the parallel trends and no anticipation assumptions
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI   N     Switchers
Placebo_1   -0.0005991 0.0056316 -0.0116370 0.0104388 4,418   902
Placebo_2    0.0014167 0.0045867 -0.0075731 0.0104065 2,764   746
Placebo_3   -0.0007862 0.0041218 -0.0088649 0.0072925 1,636   604
Placebo_4    0.0002207 0.0049558 -0.0094925 0.0099339   907   441

Test of joint nullity of the placebos : p-value = 0.9922</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_fig81_nonnormalized_es.png" class="img-fluid figure-img"></p>
<figcaption>Stata Event Study</figcaption>
</figure>
</div>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtDYN); <span class="fu">library</span>(ggplot2)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>gq4 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">effects =</span> <span class="dv">4</span>, <span class="at">placebo =</span> <span class="dv">4</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"figures/ch08_fig81_nonnormalized_es_R.png"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot =</span> gq4<span class="sc">$</span>plot, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.0144244 0.0042477 0.0060990 0.0227498 5,674 1,119
Effect_2     0.0190899 0.0058429 0.0076380 0.0305418 4,648 1,054
Effect_3     0.0207147 0.0079164 0.0051987 0.0362307 3,750   984
Effect_4     0.0272653 0.0097924 0.0080724 0.0464582 2,980   917

Joint nullity of effects : p = 0.0068
Av_tot_eff = 0.0160565 (SE = 0.0047761)

Placebo_1   -0.0005991 0.0056316   4,418   902
Placebo_2    0.0014167 0.0045867   2,764   746
Placebo_3   -0.0007862 0.0041218   1,636   604
Placebo_4    0.0002207 0.0049558     907   441

Joint nullity of placebos : p = 0.9922</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_fig81_nonnormalized_es_R.png" class="img-fluid figure-img"></p>
<figcaption>R Event Study</figcaption>
</figure>
</div>
</div>
<div id="tabset-5-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> did_multiplegt_dyn.did_multiplegt_dyn <span class="im">import</span> DidMultiplegtDyn</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>df_pl <span class="op">=</span> pl.from_pandas(df)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>gq4 <span class="op">=</span> DidMultiplegtDyn(df<span class="op">=</span>df_pl, outcome<span class="op">=</span><span class="st">"prestout"</span>, group<span class="op">=</span><span class="st">"cnty90"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    time<span class="op">=</span><span class="st">"year"</span>, treatment<span class="op">=</span><span class="st">"numdailies"</span>, effects<span class="op">=</span><span class="dv">4</span>, placebo<span class="op">=</span><span class="dv">4</span>, cluster<span class="op">=</span><span class="st">"cnty90"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>gq4.fit()<span class="op">;</span> gq4.summary()</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>gq4.plot(title<span class="op">=</span><span class="st">"Non-normalized Event Study: Gentzkow et al. (2011)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>               Block Estimate       SE LB CI UB CI      N  Switchers
            Effect_1      NaN 0.004248   NaN   NaN 5725.0     1119.0
            Effect_2      NaN 0.005843   NaN   NaN 4840.0     1054.0
            Effect_3      NaN 0.007916   NaN   NaN 4045.0      984.0
            Effect_4      NaN 0.009792   NaN   NaN 3342.0      917.0
Average_Total_Effect          0.004776             9081.0     4074.0
           Placebo_1      NaN 0.005132   NaN   NaN 4611.0      902.0
           Placebo_2      NaN 0.008503   NaN   NaN 3122.0      746.0
           Placebo_3      NaN 0.011682   NaN   NaN 2156.0      604.0
           Placebo_4      NaN 0.017503   NaN   NaN 1589.0      441.0

Note: Point estimates display NaN in py-did-multiplegt-dyn v0.1.4.
SE and N/Switchers match Stata/R. See Stata/R tabs for full results.</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_fig81_nonnormalized_es_Python.png" class="img-fluid figure-img"></p>
<figcaption>Python Event Study</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> All four non-normalized event-study effects are positive and significant, suggesting newspapers increase turnout. The effects grow with <span class="math inline">\(\ell\)</span>, from 0.0144 at <span class="math inline">\(\ell = 1\)</span> to 0.0273 at <span class="math inline">\(\ell = 4\)</span>. All placebo estimates are small and insignificant, with a joint p-value of 0.9922, strongly supporting the parallel-trends assumption. The average cumulative effect per treatment unit is 0.0161 (SE = 0.0048).</p>
<p><em>Figure 8.1: Non-normalized DID estimates of the effect of being exposed to a weakly larger number of newspapers for <span class="math inline">\(\ell\)</span> periods on turnout. Standard errors clustered at the county level. 95% confidence intervals shown in red.</em></p>
<hr>
</section>
<section id="gq5-8.3.5-treatment-path-descriptions" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="gq5-8.3.5-treatment-path-descriptions"><span class="header-section-number">6.7</span> GQ5 (§8.3.5): Treatment Path Descriptions</h2>
<blockquote class="blockquote">
<p>Rerun <code>did_multiplegt_dyn</code> with <code>design(0.8,console)</code> for <span class="math inline">\(\ell = 1, 2, 4\)</span>. What are the three most common “actual-versus-status-quo” comparisons averaged in <span class="math inline">\(AVSQ_\ell\)</span>?</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-3" role="tab" aria-controls="tabset-6-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(1) design(0.8,<span class="kw">console</span>) graph_off</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(2) design(0.8,<span class="kw">console</span>) graph_off</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(4) design(0.8,<span class="kw">console</span>) graph_off</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>--- ℓ = 1 (1,126 switchers) ---
  TreatPath1:  721 groups (64.03%), treatment vector (0 → 1)
  TreatPath2:  139 groups (12.34%), treatment vector (0 → 2)
  TreatPath3:   54 groups ( 4.80%), treatment vector (1 → 2)
  Top 3 cover 81.17% of switchers

--- ℓ = 2 (1,067 switchers) ---
  TreatPath1: 343 groups (32.15%), vector (0,1,1) vs (0,0,0)
  TreatPath2: 187 groups (17.53%), vector (0,1,0) vs (0,0,0)
  9 paths, top paths cover 81.54% of switchers

--- ℓ = 4 (933 switchers) ---
  TreatPath1: 141 groups (15.11%), vector (0,1,1,1,1) vs (0,0,0,0,0)
  56 treatment paths detected
  Top paths cover 80.17% of switchers</code></pre>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># design() triggers a data.table join bug in DIDmultiplegtDYN (R):</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Error: "columns to join by must be specified using 'on=' argument"</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Workaround: run without design() to verify effects match Stata.</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>gq5_l1 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">effects =</span> <span class="dv">1</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span>, <span class="at">graph_off =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>gq5_l2 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">effects =</span> <span class="dv">2</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span>, <span class="at">graph_off =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>gq5_l4 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">effects =</span> <span class="dv">4</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span>, <span class="at">graph_off =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Effects (without design paths — design() bug in R):
  ℓ = 1: Effect_1 = 0.0144244 (SE = 0.0042477), N = 5,674, Switchers = 1,119
  ℓ = 2: Effect_1 = 0.0143314 (SE = 0.0042477), N = 5,674, Switchers = 1,119
  ℓ = 4: Effect_1 = 0.0160565 (SE = 0.0047761), N = 5,674, Switchers = 1,119

Note: Effects match Stata exactly. Treatment path tables require design(),
which is Stata-only due to the R data.table bug.</code></pre>
</div>
<div id="tabset-6-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># design() option not available in py-did-multiplegt-dyn.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Run effects(1), effects(2), effects(4) without design paths.</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ell <span class="kw">in</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>]:</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> DidMultiplegtDyn(df<span class="op">=</span>df_pl, outcome<span class="op">=</span><span class="st">"prestout"</span>, group<span class="op">=</span><span class="st">"cnty90"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>        time<span class="op">=</span><span class="st">"year"</span>, treatment<span class="op">=</span><span class="st">"numdailies"</span>, effects<span class="op">=</span>ell, cluster<span class="op">=</span><span class="st">"cnty90"</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    m.fit()<span class="op">;</span> m.summary()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Effects (without design paths — design() not available in Python):
  ℓ = 1: Effect_1 SE = 0.004248, N = 5,725, Switchers = 1,119
  ℓ = 2: Effect_1 SE = 0.004248, N = 5,725, Switchers = 1,119
  ℓ = 4: Effect_1 SE = 0.004776, N = 5,725, Switchers = 1,119

Note: Point estimates display NaN (v0.1.4 bug). SE and N/Switchers match
Stata/R. Treatment path tables are Stata-only.</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> At <span class="math inline">\(\ell = 1\)</span>, most switchers transition from 0 to 1 newspaper (64%). As <span class="math inline">\(\ell\)</span> increases, the treatment paths become more heterogeneous: by <span class="math inline">\(\ell = 4\)</span>, the top 3 paths account for only about 34% of all effects. Some counties gain newspapers and keep them, others gain and lose them. This heterogeneity complicates interpretation of <span class="math inline">\(AVSQ_\ell\)</span> at longer horizons.</p>
<hr>
</section>
<section id="gq6-8.3.5-normalized-event-study-effects-figure-8.2" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="gq6-8.3.5-normalized-event-study-effects-figure-8.2"><span class="header-section-number">6.8</span> GQ6 (§8.3.5): Normalized Event-Study Effects (Figure 8.2)</h2>
<blockquote class="blockquote">
<p>Compute normalized event-study estimates <span class="math inline">\(\widehat{AVSQ}^n_\ell\)</span> for <span class="math inline">\(\ell \in \{1, \ldots, 4\}\)</span> and normalized pre-trends. Test whether all normalized effects are equal. Produce Figure 8.2.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-3" role="tab" aria-controls="tabset-7-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(4) placebo(4) normalized effects_equal(<span class="ot">all</span>) <span class="kw">cluster</span>(cnty90)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="kw">graph</span> <span class="kw">export</span> <span class="st">"$FIGDIR\ch08_fig82_normalized_es.png"</span>, <span class="kw">replace</span> <span class="kw">width</span>(1200)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.0120186 0.0035392 0.0050818 0.0189554 5,674 1,119
Effect_2     0.0082126 0.0025136 0.0032860 0.0131392 4,648 1,054
Effect_3     0.0057192 0.0021857 0.0014353 0.0100031 3,750   984
Effect_4     0.0053873 0.0019348 0.0015951 0.0091795 2,980   917

Test of joint nullity of the effects : p-value = 0.0068
Test of equality of the effects : p-value = 0.1653

Weights wℓ,k (effect of kth treatment lag):
  ℓ=1: w1,0 = 1.00
  ℓ=2: w2,0 = 0.48, w2,1 = 0.52
  ℓ=3: w3,0 = 0.35, w3,1 = 0.31, w3,2 = 0.33
  ℓ=4: w4,0 = 0.28, w4,1 = 0.26, w4,2 = 0.23, w4,3 = 0.24

Average cumulative (total) effect per treatment unit:
  0.0160565 (SE = 0.0047761)

----------------------------------------------------------------------
     Testing the parallel trends and no anticipation assumptions
----------------------------------------------------------------------
             Estimate SE      LB CI    UB CI   N     Switchers
Placebo_1   -0.0004159 0.0042471 -0.0087401 0.0079083 4,418   902
Placebo_2    0.0008718 0.0035930 -0.0061704 0.0079140 2,764   746
Placebo_3   -0.0004199 0.0031938 -0.0066796 0.0058398 1,636   604
Placebo_4    0.0001368 0.0037130 -0.0071406 0.0074142   907   441

Test of joint nullity of the placebos : p-value = 0.9922</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_fig82_normalized_es.png" class="img-fluid figure-img"></p>
<figcaption>Stata Normalized ES</figcaption>
</figure>
</div>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>gq6 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">effects =</span> <span class="dv">4</span>, <span class="at">placebo =</span> <span class="dv">4</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">normalized =</span> <span class="cn">TRUE</span>, <span class="at">effects_equal =</span> <span class="cn">TRUE</span>, <span class="at">cluster =</span> <span class="st">"cnty90"</span>)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"figures/ch08_fig82_normalized_es_R.png"</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">plot =</span> gq6<span class="sc">$</span>plot, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">dpi =</span> <span class="dv">150</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.0120186 0.0035392 0.0050818 0.0189554 5,674 1,119
Effect_2     0.0082126 0.0025136 0.0032860 0.0131392 4,648 1,054
Effect_3     0.0057192 0.0021857 0.0014353 0.0100031 3,750   984
Effect_4     0.0053873 0.0019348 0.0015951 0.0091795 2,980   917

Joint nullity of effects : p = 0.0068
Equality of effects : p = 0.1653
Av_tot_eff = 0.0160565 (SE = 0.0047761)

Placebo_1   -0.0004159 0.0042471   4,418   902
Placebo_2    0.0008718 0.0035930   2,764   746
Placebo_3   -0.0004199 0.0031938   1,636   604
Placebo_4    0.0001368 0.0037130     907   441

Joint nullity of placebos : p = 0.9922</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_fig82_normalized_es_R.png" class="img-fluid figure-img"></p>
<figcaption>R Normalized ES</figcaption>
</figure>
</div>
</div>
<div id="tabset-7-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>gq6 <span class="op">=</span> DidMultiplegtDyn(df<span class="op">=</span>df_pl, outcome<span class="op">=</span><span class="st">"prestout"</span>, group<span class="op">=</span><span class="st">"cnty90"</span>,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    time<span class="op">=</span><span class="st">"year"</span>, treatment<span class="op">=</span><span class="st">"numdailies"</span>, effects<span class="op">=</span><span class="dv">4</span>, placebo<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    normalized<span class="op">=</span><span class="va">True</span>, effects_equal<span class="op">=</span><span class="va">True</span>, cluster<span class="op">=</span><span class="st">"cnty90"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>gq6.fit()<span class="op">;</span> gq6.summary()</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>gq6.plot(title<span class="op">=</span><span class="st">"Normalized Event Study: Gentzkow et al. (2011)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>               Block Estimate       SE LB CI UB CI      N  Switchers
            Effect_1      NaN 0.003539   NaN   NaN 5725.0     1119.0
            Effect_2      NaN 0.002514   NaN   NaN 4840.0     1054.0
            Effect_3      NaN 0.002186   NaN   NaN 4045.0      984.0
            Effect_4      NaN 0.001935   NaN   NaN 3342.0      917.0
Average_Total_Effect          0.004776             9081.0     4074.0
           Placebo_1      NaN 0.004247   NaN   NaN 4611.0      902.0
           Placebo_2      NaN 0.003593   NaN   NaN 3122.0      746.0
           Placebo_3      NaN 0.003194   NaN   NaN 2156.0      604.0
           Placebo_4      NaN 0.003713   NaN   NaN 1589.0      441.0

Note: Point estimates display NaN in py-did-multiplegt-dyn v0.1.4.
SE and N/Switchers match Stata/R. See Stata/R tabs for full results.</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/ch08_fig82_normalized_es_Python.png" class="img-fluid figure-img"></p>
<figcaption>Python Normalized ES</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Normalized effects are decreasing with <span class="math inline">\(\ell\)</span> (from 0.0120 to 0.0054), but the equality test cannot reject the null (<span class="math inline">\(p = 0.1653\)</span>). The weights <span class="math inline">\(w_{\ell,k}\)</span> are approximately equal across lags within each <span class="math inline">\(\ell\)</span>: for <span class="math inline">\(\ell = 4\)</span>, the weight on contemporaneous newspapers (<span class="math inline">\(w_{4,0} = 0.28\)</span>) is similar to that on the third lag (<span class="math inline">\(w_{4,3} = 0.24\)</span>). The decreasing pattern of normalized effects may suggest that lagged newspapers have a smaller effect than contemporaneous newspapers.</p>
<p><em>Figure 8.2: Normalized DID estimates of effects of newspapers on turnout. Standard errors clustered at the county level. 95% confidence intervals shown in red.</em></p>
<hr>
</section>
<section id="gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="gq7-8.4.10-ats-and-wats-estimators-did_multiplegt_stat"><span class="header-section-number">6.9</span> GQ7 (§8.4.10): ATS and WATS Estimators (<code>did_multiplegt_stat</code>)</h2>
<blockquote class="blockquote">
<p>Using <code>did_multiplegt_stat</code>, compute the ATS and WATS estimators with <code>exact_match</code> and one placebo. Compare to the normalized event-study effects.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-3" role="tab" aria-controls="tabset-8-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_stat prestout cnty90 <span class="fu">year</span> numdailies, <span class="co">///</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    placebo(1) exact_match</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>-----------------------------------
N                =            15466
WAOSS Method     =  Reg. Adjustment
Common Support   =   Exact Matching
-----------------------------------

----------------------------------------------------------------------
                    Estimation of AOSS(s)
----------------------------------------------------------------------
     Estimate    SE      LB CI   UB CI   Switchers Stayers
AOSS 0.0060678 0.0016463 0.0028411 0.0092945 4,423  11,043

----------------------------------------------------------------------
               Estimation of AOSS(s) - Placebo
----------------------------------------------------------------------
     Estimate     SE      LB CI    UB CI   Switchers Stayers
AOSS -0.0011278 0.0025056 -0.0060387 0.0037831 2,349   7,764

----------------------------------------------------------------------
                    Estimation of WAOSS(s)
----------------------------------------------------------------------
      Estimate    SE      LB CI   UB CI   Switchers Stayers
WAOSS 0.0057351 0.0015079 0.0027796 0.0086906 4,423  11,043

----------------------------------------------------------------------
               Estimation of WAOSS(s) - Placebo
----------------------------------------------------------------------
      Estimate     SE      LB CI    UB CI   Switchers Stayers
WAOSS -0.0000123 0.0022931 -0.0045067 0.0044821 2,349   7,764

141 switchers dropped (baseline treatment not in stayers' support)
22 stayers dropped (baseline treatment not in switchers' support)</code></pre>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DIDmultiplegtSTAT)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># devtools::install_github("chaisemartinPackages/did_multiplegt_stat/R", force = TRUE)</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>gq7 <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_stat</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> <span class="fu">as.data.frame</span>(df),</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y =</span> <span class="st">"prestout"</span>, <span class="at">ID =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Time =</span> <span class="st">"year"</span>, <span class="at">D =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">placebo =</span> <span class="cn">TRUE</span>, <span class="at">exact_match =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gq7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>-----------------------------------
N                =            15466
WAOSS Method     =  Reg. Adjustment
Common Support   =   Exact Matching
-----------------------------------

----------------------------------------------------------------------
                    Estimation of AOSS(s)
----------------------------------------------------------------------
     Estimate SE      LB CI   UB CI   Switchers Stayers
AOSS 0.00624  0.00143 0.00343 0.00904 4,423     11,043

----------------------------------------------------------------------
               Estimation of AOSS(s) - Placebo
----------------------------------------------------------------------
     Estimate SE      LB CI    UB CI   Switchers Stayers
AOSS -0.00092 0.00147 -0.00381 0.00196 2,287     7,743

----------------------------------------------------------------------
                    Estimation of WAOSS(s)
----------------------------------------------------------------------
      Estimate SE      LB CI   UB CI   Switchers Stayers
WAOSS 0.00590  0.00130 0.00335 0.00846 4,423     11,043

----------------------------------------------------------------------
               Estimation of WAOSS(s) - Placebo
----------------------------------------------------------------------
      Estimate SE      LB CI    UB CI   Switchers Stayers
WAOSS 0.00022  0.00134 -0.00241 0.00284 2,287     7,743

203 switchers dropped | 43 stayers dropped</code></pre>
</div>
<div id="tabset-8-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># py_did_multiplegt_stat (local notebook-based translation)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Located at: C:\...\py_did_multiplegt_stat\stat_python</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> did_multiplegt_stat(</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    df<span class="op">=</span>df, Y<span class="op">=</span><span class="st">"prestout"</span>, ID<span class="op">=</span><span class="st">"cnty90"</span>, Time<span class="op">=</span><span class="st">"year"</span>, D<span class="op">=</span><span class="st">"numdailies"</span>,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    estimator<span class="op">=</span>[<span class="st">"aoss"</span>,<span class="st">"waoss"</span>], estimation_method<span class="op">=</span><span class="st">"ra"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    placebo<span class="op">=</span><span class="va">True</span>, exact_match<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>summary_did_multiplegt_stat(res)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>-----------------------------------
N                =            15466
WAOSS Method     =  Reg. Adjustment
Common Support   =   Exact Matching
-----------------------------------

----------------------------------------------------------------------
                    Estimation of AOSS(s)
----------------------------------------------------------------------
       Estimate         SE       LB CI      UB CI Switchers Stayers
AOSS  0.0013877  0.0017021  -0.0019483  0.0047238     4,423  11,043

----------------------------------------------------------------------
               Estimation of AOSS(s) - Placebo
----------------------------------------------------------------------
        Estimate         SE       LB CI      UB CI Switchers Stayers
AOSS  -0.0002455  0.0017037  -0.0035848  0.0030938     2,287   7,743

----------------------------------------------------------------------
                    Estimation of WAOSS(s)
----------------------------------------------------------------------
        Estimate         SE      LB CI      UB CI Switchers Stayers
WAOSS  0.0053390  0.0015438  0.0023132  0.0083648     4,423  11,043

----------------------------------------------------------------------
               Estimation of WAOSS(s) - Placebo
----------------------------------------------------------------------
         Estimate         SE       LB CI      UB CI Switchers Stayers
WAOSS  -0.0002959  0.0015641  -0.0033616  0.0027698     2,287   7,743

Note: AOSS differs from Stata/R; WAOSS closer. Implementation differences
in matching/weighting algorithms across platforms. See Stata tab as reference.</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> Both ATS (<span class="math inline">\(\approx 0.006\)</span>) and WATS (<span class="math inline">\(\approx 0.006\)</span>) are significant and positive in Stata and R. The placebo estimates are small and insignificant, supporting the parallel-trends assumption. These estimates are roughly half the magnitude of <span class="math inline">\(\widehat{AVSQ}^n_1 = 0.012\)</span>, which suggests a non-linear treatment response: the average effect per unit of treatment change is smaller when computed across all switcher magnitudes.</p>
<p>Note: Stata, R, and Python point estimates differ slightly due to internal implementation variations (matching algorithms, variance formulas). N, switchers, and stayers are identical across all three.</p>
<hr>
</section>
<section id="bonus-joint-test-of-no-dynamic-effects" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="bonus-joint-test-of-no-dynamic-effects"><span class="header-section-number">6.10</span> Bonus: Joint Test of No Dynamic Effects</h2>
<blockquote class="blockquote">
<p>Restrict to counties whose treatment does not change between <span class="math inline">\(F_g\)</span> and <span class="math inline">\(F_g + 1\)</span>, and test whether the first and second non-normalized effects are equal.</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true" href="">Stata</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false" href="">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-3" role="tab" aria-controls="tabset-9-3" aria-selected="false" href="">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb48"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>did_multiplegt_dyn prestout cnty90 <span class="fu">year</span> numdailies <span class="co">///</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">if</span> <span class="fu">year</span>&lt;=first_change | same_treat_after_first_change==1, <span class="co">///</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">effects</span>(2) effects_equal(<span class="ot">all</span>) same_switchers graph_off</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>----------------------------------------------------------------------
       Estimation of treatment effects: Event-study effects
----------------------------------------------------------------------
             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01526  0.00549 0.00449 0.02603 3,718   512
Effect_2     0.01637  0.00645 0.00374 0.02901 3,718   512

Test of equality of the effects : p-value = 0.8301</code></pre>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>df_sub <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, year <span class="sc">&lt;=</span> first_change <span class="sc">|</span> same_treat_after_first_change <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>bonus <span class="ot">&lt;-</span> <span class="fu">did_multiplegt_dyn</span>(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df_sub, <span class="at">outcome =</span> <span class="st">"prestout"</span>, <span class="at">group =</span> <span class="st">"cnty90"</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="st">"year"</span>, <span class="at">treatment =</span> <span class="st">"numdailies"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">effects =</span> <span class="dv">2</span>, <span class="at">effects_equal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">same_switchers =</span> <span class="cn">TRUE</span>, <span class="at">graph_off =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01526  0.00549 0.00449 0.02603 3,718   512
Effect_2     0.01637  0.00645 0.00374 0.02901 3,718   512

Test of equality of the effects : p-value = 0.8301</code></pre>
</div>
<div id="tabset-9-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-3-tab">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Python did_multiplegt_dyn returns NaN for point estimates in v0.1.4.</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Stata/R results shown for reference.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>             Estimate SE      LB CI   UB CI   N     Switchers
Effect_1     0.01526  0.00549 0.00449 0.02603 3,718   512
Effect_2     0.01637  0.00645 0.00374 0.02901 3,718   512
Equality of effects : p = 0.8301</code></pre>
</div>
</div>
</div>
<p><strong>Interpretation:</strong> In the subsample of 512 counties whose treatment does not change between <span class="math inline">\(F_g\)</span> and <span class="math inline">\(F_g + 1\)</span>, the first and second event-study effects are very close (0.015 vs 0.016) and not significantly different (<span class="math inline">\(p = 0.83\)</span>). This is consistent with the joint null that the first lag of newspapers does not affect turnout and that treatment effects are constant over time.</p>
<hr>
</section>
<section id="summary-of-results" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="summary-of-results"><span class="header-section-number">6.11</span> Summary of Results</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 30%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">GQ</th>
<th style="text-align: center;">Method</th>
<th style="text-align: left;">Key Finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">GQ1</td>
<td style="text-align: center;">OLS</td>
<td style="text-align: left;"><span class="math inline">\(\Delta D\)</span> and <span class="math inline">\(D_1\)</span> are correlated (<span class="math inline">\(\beta = -0.0420\)</span>, <span class="math inline">\(p = 0.008\)</span>) → possible OVB</td>
</tr>
<tr class="even">
<td style="text-align: center;">GQ2</td>
<td style="text-align: center;">OLS</td>
<td style="text-align: left;">Urbanization predicts <span class="math inline">\(\Delta D\)</span> (<span class="math inline">\(\beta = -0.1422\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>) → not as-good-as-random</td>
</tr>
<tr class="odd">
<td style="text-align: center;">GQ3</td>
<td style="text-align: center;">Distributed-lag TWFE</td>
<td style="text-align: left;">Current effect NS (<span class="math inline">\(-0.0008\)</span>), lag significant (<span class="math inline">\(0.0050\)</span>); severe negative weights (<span class="math inline">\(\Sigma = -0.85\)</span>) and cross-contamination (<span class="math inline">\(\Sigma = \pm 1.21\)</span>)</td>
</tr>
<tr class="even">
<td style="text-align: center;">GQ4</td>
<td style="text-align: center;"><code>did_multiplegt_dyn</code></td>
<td style="text-align: left;">All effects positive &amp; significant; placebos NS (joint <span class="math inline">\(p = 0.992\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">GQ5</td>
<td style="text-align: center;"><code>design</code> option</td>
<td style="text-align: left;">Treatment paths increasingly heterogeneous as <span class="math inline">\(\ell\)</span> grows</td>
</tr>
<tr class="even">
<td style="text-align: center;">GQ6</td>
<td style="text-align: center;">Normalized ES</td>
<td style="text-align: left;">Decreasing effects; cannot reject equality (<span class="math inline">\(p = 0.165\)</span>); roughly equal lag weights</td>
</tr>
<tr class="odd">
<td style="text-align: center;">GQ7</td>
<td style="text-align: center;"><code>did_multiplegt_stat</code></td>
<td style="text-align: left;">ATS ≈ WATS ≈ 0.006 (significant); placebos NS</td>
</tr>
<tr class="even">
<td style="text-align: center;">Bonus</td>
<td style="text-align: center;">No-dynamics test</td>
<td style="text-align: left;">Effects 1 &amp; 2 not different (<span class="math inline">\(p = 0.83\)</span>) → consistent with no dynamic effects</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch07.html" class="pagination-link" aria-label="Chapter 7: Designs with Variation in Treatment Dose">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 7: Designs with Variation in Treatment Dose</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>